#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extra vragen voor dunne sets zodat elke set >= 100 vragen telt."""

EXTRA = {
    'afrika': [
        ('Geografie', 'Hoeveel landen grenzen aan Zuid-Afrika?', 6),
        ('Geografie', 'Hoeveel landen grenzen aan Kenia?', 5),
        ('Geografie', 'Hoeveel landen grenzen aan Tanzania?', 8),
        ('Geografie', 'Hoeveel landen grenzen aan Egypte?', 4),
        ('Geografie', 'Hoeveel landen grenzen aan Niger?', 7),
        ('Geografie', 'Hoeveel landen grenzen aan Mali?', 7),
        ('Geografie', 'Hoeveel landen grenzen aan Algerije?', 7),
        ('Geografie', 'Hoeveel landen grenzen aan Libië?', 6),
        ('Geografie', 'Hoeveel landen grenzen aan Soedan?', 7),
        ('Geografie', 'Hoeveel landen grenzen aan Ethiopië?', 6),
        ('Geografie', 'Hoeveel landen grenzen aan Congo-Kinshasa?', 9),
        ('Geografie', 'Hoeveel landen grenzen aan Angola?', 4),
        ('Geografie', 'Hoeveel landen grenzen aan Mozambique?', 6),
        ('Geografie', 'Hoeveel landen grenzen aan Nigeria?', 4),
        ('Geografie', 'Hoeveel landen grenzen aan Ghana?', 3),
        ('Geografie', 'Hoeveel landen grenzen aan Kameroen?', 6),
        ('Geografie', 'Hoeveel landen grenzen aan Tsjaad?', 6),
        ('Geografie', 'Hoeveel landen grenzen aan Oeganda?', 5),
        ('Geografie', 'Hoeveel Afrikaanse landen liggen aan de Rode Zee?', 6),
        ('Geografie', 'Hoeveel kilometer lang is de Kongorivier bij benadering (in duizenden km afgerond)?', 5),
        ('Geografie', 'Hoeveel kilometer lang is de Nigerrivier bij benadering (in duizenden km afgerond)?', 4),
        ('Geografie', 'Hoeveel kilometer lang is de Zambezirivier bij benadering (in duizenden km afgerond)?', 3),
        ('Geografie', 'Hoeveel meter hoog is Mount Kenya afgerond op honderdtallen?', 5200),
        ('Geografie', 'Hoeveel meter hoog is de Toubkal, hoogste piek van het Atlasgebergte, afgerond op honderdtallen?', 4200),
        ('Geschiedenis', 'In welk jaar werd Kenia onafhankelijk van Groot-Brittannië?', 1963),
        ('Geschiedenis', 'In welk jaar werd Nigeria onafhankelijk?', 1960),
        ('Geschiedenis', 'In welk jaar werd Ghana als eerste Afrikaanse kolonie onafhankelijk?', 1957),
        ('Geschiedenis', 'In welk jaar had Zuid-Afrika zijn eerste vrije verkiezingen na de apartheid?', 1994),
        ('Geschiedenis', 'Hoeveel jaar duurde de Biafra-oorlog?', 3),
        ('Geschiedenis', 'Hoeveel keer meer pyramides telt Soedan dan Egypte bij benadering?', 2),
        ('Dieren', 'Hoeveel kilometer per uur sprint een leeuw afgerond op tientallen?', 80),
        ('Dieren', 'Hoeveel kilogram weegt een volwassen witte neushoorn afgerond op duizendtallen?', 2000),
        ('Dieren', 'Hoeveel kilogram weegt een volwassen giraffe afgerond op honderdtallen?', 1200),
        ('Dieren', 'Hoeveel meter lang wordt een Afrikaanse olifant afgerond op hele meters?', 7),
        ('Dieren', 'Hoeveel soorten lemuren telt Madagaskar bij benadering (in tientallen)?', 100),
        ('Eten & drinken', 'Hoeveel procent van de wereldcacao komt uit West-Afrika afgerond op tientallen?', 70),
        ('Milieu en duurzaamheid', 'Hoeveel miljoen gnoes doen mee aan de Grote Migratie in de Serengeti (afgerond op miljoenen)?', 2),
        ('Politiek en recht', 'Hoeveel zetels telt het Zuid-Afrikaanse parlement (National Assembly)?', 400),
        ('Politiek en recht', 'Hoeveel officiële talen telt Zuid-Afrika sinds 2023?', 12),
        ('Muziek', 'Hoeveel snaren heeft de Ethiopische krar bij benadering (in tientallen afgerond)?', 10),
    ],
    'oceanie': [
        ('Geografie', 'Hoeveel landen liggen er in Melanesië?', 4),
        ('Geografie', 'Hoeveel tijdzones heeft Australië?', 3),
        ('Geografie', 'Hoeveel tijdzones heeft Nieuw-Zeeland?', 2),
        ('Geografie', 'Hoeveel meter hoog is Mount Kosciuszko, het hoogste punt van Australië, afgerond op honderdtallen?', 2200),
        ('Geografie', 'Hoeveel kilometer lang is de Murrayrivier bij benadering (in duizenden km afgerond)?', 3),
        ('Geografie', 'Hoeveel procent van Australië bestaat uit woestijn of droog gebied (afgerond op tientallen)?', 70),
        ('Geografie', 'Hoeveel miljoen inwoners heeft Australië (2024, afgerond)?', 27),
        ('Geografie', 'Hoeveel miljoen inwoners heeft Nieuw-Zeeland (2024, afgerond)?', 5),
        ('Geografie', 'Hoeveel staatjes telt Micronesië als federatie?', 4),
        ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is de Sydney Tower afgerond op tientallen?', 310),
        ('Gebouwen en infrastructuur', 'Hoeveel verdiepingen heeft de Eureka Tower in Melbourne?', 91),
        ('Dieren', 'Hoeveel soorten vogels telt Australië bij benadering (in honderden afgerond)?', 800),
        ('Dieren', 'Hoeveel kilogram weegt een volwassen emoe afgerond op tientallen?', 50),
        ('Dieren', 'Hoeveel eieren legt een kangoeroe per worp?', 0),
        ('Dieren', 'Hoeveel uur per dag slaapt een koala afgerond op tientallen?', 20),
        ('Dieren', 'Hoeveel meter lang wordt een zoutwaterkrokodil maximaal afgerond op hele meters?', 6),
        ('Dieren', 'Hoeveel kilogram weegt een volwassen wombat afgerond op tientallen?', 30),
        ('Sport', 'Hoeveel keer was Australië gastheer van de zomer-Olympische Spelen (tot 2032)?', 3),
        ('Sport', 'Hoeveel keer was Nieuw-Zeeland gastheer van de Rugby World Cup bij de mannen?', 2),
        ('Sport', 'Hoeveel gouden medailles won Australië op de Olympische Zomerspelen 2024?', 18),
        ('Muziek', 'Hoeveel studioalbums bracht Kylie Minogue uit bij benadering (in tientallen afgerond)?', 15),
        ('Films en series', 'Hoeveel Oscars won de film The Piano (1993)?', 3),
        ('Films en series', 'Hoeveel Oscars won Gladiator (2000)?', 5),
        ('Politiek en recht', 'Hoeveel staten en territoria telt Australië samen?', 8),
        ('Politiek en recht', 'Hoeveel jaar duurt een termijn van het Australische Huis van Afgevaardigden?', 3),
        ('Politiek en recht', 'Hoeveel jaar duurt een termijn van het Nieuw-Zeelandse parlement?', 3),
    ],
    'latijns_amerika': [
        ('Geografie', 'Hoeveel landen grenzen aan Bolivia?', 5),
        ('Geografie', 'Hoeveel landen grenzen aan Venezuela?', 3),
        ('Geografie', 'Hoeveel landen grenzen aan Ecuador?', 2),
        ('Geografie', 'Hoeveel landen grenzen aan Paraguay?', 3),
        ('Geografie', 'Hoeveel landen grenzen aan Uruguay?', 2),
        ('Geografie', 'Hoeveel landen grenzen aan Chili?', 3),
        ('Geografie', 'Hoeveel landen grenzen aan Guatemala?', 4),
        ('Geografie', 'Hoeveel landen grenzen aan Panama?', 2),
        ('Geografie', 'Hoeveel landen grenzen aan Honduras?', 3),
        ('Geografie', 'Hoeveel landen grenzen aan Nicaragua?', 2),
        ('Geografie', 'Hoeveel landen grenzen aan Costa Rica?', 2),
        ('Geografie', 'Hoeveel miljoen inwoners heeft Brazilië (2024, afgerond op honderdtallen)?', 200),
        ('Geografie', 'Hoeveel miljoen inwoners heeft Mexico (2024, afgerond op honderdtallen)?', 100),
        ('Geografie', 'Hoeveel miljoen inwoners heeft Argentinië (2024, afgerond op tientallen)?', 50),
        ('Geografie', 'Hoeveel miljoen inwoners heeft Colombia (2024, afgerond op tientallen)?', 50),
        ('Geografie', 'Hoeveel miljoen inwoners heeft Peru (2024, afgerond op tientallen)?', 30),
        ('Geografie', 'Hoeveel miljoen inwoners heeft Chili (2024, afgerond op tientallen)?', 20),
        ('Geografie', 'Hoeveel duizend meter hoog ligt het Titicacameer boven zeeniveau (in duizenden afgerond)?', 4),
        ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is Christus Redentor inclusief sokkel afgerond op tientallen?', 40),
        ('Gebouwen en infrastructuur', 'Hoeveel stappen telt de Mayapyramide El Castillo per zijde?', 91),
        ('Gebouwen en infrastructuur', 'Hoeveel stappen telt El Castillo van Chichen Itza in totaal inclusief de top?', 365),
        ('Geschiedenis', 'In welk jaar werd Mexico onafhankelijk van Spanje?', 1821),
        ('Geschiedenis', 'In welk jaar werd Peru onafhankelijk van Spanje?', 1821),
        ('Geschiedenis', 'In welk jaar werd Argentinië onafhankelijk van Spanje?', 1816),
        ('Geschiedenis', 'In welk jaar werd Chili onafhankelijk van Spanje?', 1818),
        ('Geschiedenis', 'In welk jaar werd Colombia onafhankelijk van Spanje?', 1810),
        ('Geschiedenis', 'In welk jaar werd Venezuela onafhankelijk van Spanje?', 1811),
        ('Geschiedenis', 'In welk jaar werd Bolivia onafhankelijk van Spanje?', 1825),
        ('Geschiedenis', 'In welk jaar werd Paraguay onafhankelijk van Spanje?', 1811),
        ('Dieren', 'Hoeveel soorten vogels telt Colombia bij benadering (in honderden afgerond)?', 1900),
        ('Dieren', 'Hoeveel kilometer per uur sprint een jaguar afgerond op tientallen?', 80),
        ('Dieren', 'Hoeveel meter lang kan een groene anaconda worden (in hele meters afgerond)?', 6),
        ('Eten & drinken', 'Hoeveel liter mate drinkt de gemiddelde Uruguayaan per jaar (in tientallen liters)?', 80),
        ('Muziek', 'Hoeveel snaren heeft de klassieke Colombiaanse tiple?', 12),
        ('Sport', 'Hoeveel keer was Mexico gastheer van de FIFA World Cup (2026 inbegrepen)?', 3),
        ('Sport', 'Hoeveel keer won Brazilië de Copa América tot 2024?', 9),
        ('Politiek en recht', 'Hoeveel departementen telt Colombia (2024)?', 32),
        ('Politiek en recht', 'Hoeveel departementen telt Peru?', 25),
        ('Politiek en recht', 'Hoeveel provincies telt Ecuador?', 24),
        ('Politiek en recht', 'Hoeveel departementen telt Bolivia?', 9),
    ],
    'sport': [
        ('Sport', 'Hoeveel spelers heeft een waterpoloteam in het water per ploeg?', 7),
        ('Sport', 'Hoeveel spelers heeft een honkbalteam op het veld per ploeg?', 9),
        ('Sport', 'Hoeveel spelers heeft een hockeyteam op het veld per ploeg?', 11),
        ('Sport', 'Hoeveel spelers heeft een basketbalteam op het veld per ploeg?', 5),
        ('Sport', 'Hoeveel spelers heeft een volleybalteam op het veld per ploeg?', 6),
        ('Sport', 'Hoeveel spelers heeft een handbalteam op het veld per ploeg?', 7),
        ('Sport', 'Hoeveel minuten duurt een ijshockeywedstrijd netto?', 60),
        ('Sport', 'Hoeveel minuten duurt een NBA-basketbalwedstrijd officieel?', 48),
        ('Sport', 'Hoeveel minuten duurt een rugbywedstrijd netto?', 80),
        ('Sport', 'Hoeveel innings telt een honkbalwedstrijd standaard?', 9),
        ('Sport', 'Hoeveel pijlen gooit een darter per beurt?', 3),
        ('Sport', 'Hoeveel punten is een maximale dartscore met drie pijlen?', 180),
        ('Sport', 'Hoeveel holes telt een standaard golfronde?', 18),
        ('Sport', 'Hoeveel kilometer lang is een marathon?', 42),
        ('Sport', 'Hoeveel kilometer lang is een halve marathon (afgerond)?', 21),
        ('Sport', 'Hoeveel meter is de klassieke sprintafstand in de atletiek?', 100),
        ('Sport', 'Hoeveel meter is de mannen-hordensprint bij de Olympische Spelen?', 110),
        ('Sport', 'Hoeveel etappes telt de Tour de France (2024)?', 21),
        ('Sport', 'Hoeveel ringen heeft het Olympische symbool?', 5),
        ('Sport', 'Hoeveel jaar zit er tussen twee zomer-Olympische Spelen?', 4),
        ('Sport', 'Hoeveel jaar zit er tussen twee WK-voetbaltoernooien?', 4),
        ('Sport', 'Hoeveel keer werd de FIFA World Cup georganiseerd tot en met 2022?', 22),
        ('Sport', 'Hoeveel landen deden mee aan het FIFA World Cup 2022?', 32),
        ('Sport', 'Hoeveel landen doen mee aan het FIFA World Cup 2026?', 48),
        ('Sport', 'Hoeveel keer won Duitsland de FIFA World Cup?', 4),
        ('Sport', 'Hoeveel keer won Italië de FIFA World Cup?', 4),
        ('Sport', 'Hoeveel keer won Uruguay de FIFA World Cup?', 2),
        ('Sport', 'Hoeveel keer won Engeland de FIFA World Cup?', 1),
        ('Sport', 'Hoeveel keer won Spanje de FIFA World Cup?', 1),
        ('Sport', 'Hoeveel Champions League-titels won Real Madrid tot 2024?', 15),
        ('Sport', 'Hoeveel Champions League-titels won AC Milan tot 2024?', 7),
        ('Sport', 'Hoeveel punten levert een touchdown zonder extra point op?', 6),
        ('Sport', 'Hoeveel punten levert een fieldgoal op in American football?', 3),
        ('Sport', 'Hoeveel punten levert een safety op in American football?', 2),
        ('Sport', 'Hoeveel pogingen heeft een gewichtheffer per discipline?', 3),
        ('Sport', 'Hoeveel meter sprintt een schaatser op de kortebaan-afstand?', 500),
    ],
}

if __name__ == '__main__':
    from collections import Counter
    for key, qs in EXTRA.items():
        print(key, len(qs))
