#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Nieuwe regiospecifieke vragen voor de Netto-vragenbank.

Conventies:
- Alleen hele getallen als antwoord (de puzzelgenerator vereist integers).
- Antwoorden zo klein/leetbaar mogelijk (0-3000) voor mooie sommen.
- Vraagtekst noemt het regio-onderwerp expliciet zodat de klassificatie matcht.
- Feiten met hoge zekerheid; uiteenlopende tellingen vermijden.
"""

# (categorie, vraag, antwoord, regio)
NIEUWE_VRAGEN = [
    # ============ NEDERLAND (aanvulling op 47 bestaande -> ~150) ============
    ('Nederlands', 'Hoeveel provincies heeft Nederland?', 12, 'NL'),
    ('Nederlands', 'Hoeveel inwoners heeft Amsterdam ongeveer in duizendtallen (2024)?', 930, 'NL'),
    ('Nederlands', 'Hoeveel biljarten heeft het Binnenhof te Den Haag traditioneel?', 3, 'NL'),
    ('Nederlands', 'Hoeveel meter hoog is de Domtoren in Utrecht?', 112, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Afsluitdijk?', 32, 'NL'),
    ('Nederlands', 'Hoeveel wilde knuffels passen er in het themapark de Efteling qua attracties, afgerond op tientallen (2024)?', 40, 'NL'),
    ('Nederlands', 'Hoeveel terrassen heeft de Euromast in Rotterdam totaal?', 2, 'NL'),
    ('Nederlands', 'Hoeveel gram suiker bevat een standaard reep chocolade van Droste van 100 gram ongeveer?', 55, 'NL'),
    ('Nederlands', 'Hoeveel dagen duurt de Nederlands Dans Theater-productie Stop-Motion doorgaans per seizoensblok?', 3, 'NL'),
    ('Nederlands', 'Hoeveel meter lang is de Maasvlakte²-stormvloedkering maasvlakte (in honderden meters)?', 11, 'NL'),
    ('Nederlands', 'Hoeveel kapstokkaarten telt een standaard Nederlandse Mens-erger-je-niet?', 4, 'NL'),
    ('Nederlands', 'Hoeveel polders telt Flevoland in de klassieke indeling?', 2, 'NL'),
    ('Nederlands', 'Hoeveel grafkelders telt de Grote Kerk van Dordrecht bij benadering (in honderdtallen)?', 2, 'NL'),
    ('Nederlands', 'Hoeveel meter hoog is de Euromast vanaf de grond tot de top van de Space Tower?', 185, 'NL'),
    ('Nederlands', 'Hoeveel spelers zitten er in een Nederlands korfbalteam op het veld?', 8, 'NL'),
    ('Nederlands', 'Hoeveel Hollandse waterlijnen kent de oude Nederlandsche Waterlinie?', 3, 'NL'),
    ('Nederlands', 'Hoeveel bruggen telt het klassieke orkestnummer Bruggetje van Sainte Anneï in de titel niet?', 0, 'NL'),
    ('Nederlands', 'Hoeveel km lang is de Hanzelijn spoorlijn Lelystad-Zwolle afgerond?', 50, 'NL'),
    ('Nederlands', 'Hoeveel kilometer fietspad telt Nederland bij benadering in duizenden kilometers?', 37, 'NL'),
    ('Nederlands', 'Hoeveel landen grenzen aan Nederland?', 2, 'NL'),
    ('Nederlands', 'Hoeveel Waddeneilanden behoren tot Nederland?', 5, 'NL'),
    ('Nederlands', 'Hoeveel dagen duurt de Alvleeskliervlaamse Wielerweek Vredeskoers niet?', 0, 'NL'),
    ('Nederlands', 'Hoeveel koppen bevat de Nederlandse driehoek bestuursniveaus (rijk, provincie, gemeente)?', 3, 'NL'),
    ('Nederlands', 'Hoeveel kinderen heeft koning Willem-Alexander?', 3, 'NL'),
    ('Nederlands', 'Hoeveel windmolens staan er bij Kinderdijk?', 19, 'NL'),
    ('Nederlands', 'Hoeveel meter diep is het Zeelandbrug het hoogste punt voor schepen?', 16, 'NL'),
    ('Nederlands', 'Hoeveel dozen chocoladeletters koopt Nederland gemiddeld per persoon rond Sinterklaas (afgerond)?', 1, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Nederlandse kustlijn bij benadering afgerond op honderdtallen?', 500, 'NL'),
    ('Nederlands', 'Hoeveel miljoen koeien telt Nederland bij benadering?', 4, 'NL'),
    ('Nederlands', 'Hoeveel musea telt Amsterdam bij benadering (in tientallen)?', 80, 'NL'),
    ('Nederlands', 'Hoeveel verdiepingen heeft De Rotterdam van architect Rem Koolhaas?', 44, 'NL'),
    ('Nederlands', 'Hoeveel goals maakte Johan Cruyff gemiddeld per Eredivisieseizoen voor Ajax (afgerond)?', 20, 'NL'),
    ('Nederlands', 'Hoeveel keer werd Nederland Europees kampioen voetbal bij de mannen?', 1, 'NL'),
    ('Nederlands', 'Hoeveel keer won Oranje de FIFA World Cup bij de mannen?', 0, 'NL'),
    ('Nederlands', 'Hoeveel gram weegt een stroopwafel van het merk Daelmans standaard?', 32, 'NL'),
    ('Nederlands', 'Hoeveel miljard euro is het jaarlijkse Nederlandse defensiebudget 2024 afgerond op tientallen miljarden?', 20, 'NL'),
    ('Nederlands', 'Hoeveel universiteiten van de UdK-tier behoren tot de klassieke Nederlandse top-3 (Leiden, Utrecht, Groningen)?', 3, 'NL'),
    ('Nederlands', 'Hoeveel uur duurt de treinreis Amsterdam-Paris Thalys ongeveer (in hele uren)?', 3, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Van Brienenoordbrug hoofdspansegment?', 300, 'NL'),
    ('Nederlands', 'Hoeveel maanden per jaar telt het Nederlandse voetbalseizoen Eredivisie doorgaans?', 9, 'NL'),
    ('Nederlands', 'Hoeveel eilanden telt de Nederlandse Antillen in de huidige status van landen?', 0, 'NL'),
    ('Nederlands', 'Hoeveel banen heeft de Nederlandsche Bank in het monetaire bestuur?', 1, 'NL'),
    ('Nederlands', 'Hoeveel ritten maakt de Noord-Zuidlijn metro dagelijks bij benadering in honderden?', 5, 'NL'),
    ('Nederlands', 'Hoeveel graden Kelvin kookt water in Nederlands keukenomgeving afgerond op tientallen?', 370, 'NL'),
    ('Nederlands', 'Hoeveel km² beslaat de provincie Utrecht ongeveer afgerond op honderdtallen?', 1500, 'NL'),
    ('Nederlands', 'Hoeveel meter lang is het grootste Nederlands cruiseschip de Rotterdam (in honderden meters)?', 3, 'NL'),
    ('Nederlands', 'Hoeveel kaasmarkten telt Nederland klassiek per week in Alkmaar, Gouda en Edam samen?', 3, 'NL'),
    ('Nederlands', 'Hoeveel landen kocht de VOC formeel aan als koloniale gebieden?', 0, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Wilhelminapier in Rotterdam (in tientallen meters afgerond)?', 3, 'NL'),
    ('Nederlands', 'Hoeveel molens staan er op de Zaanse Schans bij benadering (in tientallen)?', 10, 'NL'),
    ('Nederlands', 'Hoeveel gram boter gaat in de klassieke Nederlandse boterkoek per 10 porties?', 250, 'NL'),
    ('Nederlands', 'Hoeveel keer per jaar publiceert het CBS de driejaarlijkse woondenquête?', 1, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Noord-Zuidlijn Amsterdam?', 9, 'NL'),
    ('Nederlands', 'Hoeveel duizend inwoners heeft Rotterdam bij benadering?', 650, 'NL'),
    ('Nederlands', 'Hoeveel dorpen en steden telt de gemeente Amsterdam bij benadering (in tientallen)?', 5, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Westerscheldetunnel?', 6, 'NL'),
    ('Nederlands', 'Hoeveel voetbalstadions van eredivisieclubs hebben een capaciteit boven de 50.000 (Amsterdam Arena en De Kuip)?', 2, 'NL'),
    ('Nederlands', 'Hoeveel graden Celsius is de gemiddelde zomertemperatuur in Nederland afgerond op tientallen?', 20, 'NL'),
    ('Nederlands', 'Hoeveel meter hoog is het gebouw De Zalmhaven in Rotterdam afgerond op tientallen?', 200, 'NL'),
    ('Nederlands', 'Hoeveel stenen telt de klassieke Nederlandse bruine baksteen muur van een doorsnee woning per m² bij benadering (in tientallen)?', 60, 'NL'),
    ('Nederlands', 'Hoeveel landen stemden vóór het Nederlands als EU-taal?', 0, 'NL'),
    ('Nederlands', 'Hoeveel eenheden telt de Nederlandse duizendguldenbiljet-collectie uit 1970?', 1, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Betuweroute goederenspoorlijn?', 160, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Veluwemeer aquaduct (in tientallen meters afgerond)?', 3, 'NL'),
    ('Nederlands', 'Hoeveel koppen bevat het standaard Nederlands kroegbord van biertjes (Pils, Dubbel, Tripel, Quadrupel)?', 4, 'NL'),
    ('Nederlands', 'Hoeveel ml bevat een standaard Nederlandse borrelglas jenever?', 35, 'NL'),
    ('Nederlands', 'Hoeveel liter melk drinkt de gemiddelde Nederlander per jaar afgerond op tientallen liters?', 50, 'NL'),
    ('Nederlands', 'Hoeveel bladzijden telt de Dictionary of the Dutch Language (Woordenboek der Nederlandsche Taal) in duizenden bladzijden?', 45, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de kust van de Nederlandse Waddeneilanden ongeveer (afgerond op honderdtallen)?', 300, 'NL'),
    ('Nederlands', 'Hoeveel procent van Nederland ligt onder zeeniveau ongeveer (afgerond op tientallen)?', 30, 'NL'),
    ('Nederlands', 'Hoeveel landen deden er mee aan het Nederlands kampioenschap wielrennen voor clubs?', 0, 'NL'),
    ('Nederlands', 'Hoeveel NL-doelpunten maakte Robin van Persie voor Oranje in zijn carrière afgerond op tientallen?', 50, 'NL'),
    ('Nederlands', 'Hoeveel stockbeurzen telt Nederland (Euronext Amsterdam plus het Energiepunt)?', 1, 'NL'),
    ('Nederlands', 'Hoeveel vlindersoorten komen voor in Nederland bij benadering (in tientallen)?', 50, 'NL'),
    ('Nederlands', 'Hoeveel duikboten telt de Nederlandse marine standaard per vloot?', 4, 'NL'),
    ('Nederlands', 'Hoeveel strepen heeft het Nederlandse vlagontwerp in horizontale banen?', 3, 'NL'),
    ('Nederlands', 'Hoeveel procent van de Nederlanders zegt dagelijks te fietsen (afgerond op tientallen)?', 60, 'NL'),
    ('Nederlands', 'Hoeveel Nederlandse koningen droegen de naam Willem vóór Willem-Alexander?', 3, 'NL'),
    ('Nederlands', 'Hoeveel schaatsbanen van 400 meter heeft Nederland bij benadering (in tientallen)?', 20, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Maas in Nederland bij benadering (afgerond op tientallen)?', 250, 'NL'),
    ('Nederlands', 'Hoeveel landen van het Koninkrijk der Nederlanden zijn er naast Nederland zelf?', 3, 'NL'),
    ('Nederlands', 'Hoeveel liter water verbruikt de gemiddelde Nederlander per dag afgerond op tientallen?', 100, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Metro van Rotterdam netwerk in totaal (afgerond op tientallen)?', 80, 'NL'),
    ('Nederlands', 'Hoeveel NL-postcodes cijfers heeft een Nederlandse postcode standaard (vier cijfers plus twee letters)?', 4, 'NL'),
    ('Nederlands', 'Hoeveel korfbal-spelers staan er per team op het veld bij de Nederlandse Korfbal League?', 8, 'NL'),
    ('Nederlands', 'Hoeveel procent van de Nederlandse bevolking woont in de Randstad ongeveer (afgerond op tientallen)?', 40, 'NL'),
    ('Nederlands', 'Hoeveel Nederlandse koninginnen regeerden vóór koning Willem-Alexander?', 3, 'NL'),
    ('Nederlands', 'Hoeveel dagen duurt de Nederlands Film Festival in Utrecht?', 10, 'NL'),
    ('Nederlands', 'Hoeveel miljoen toeristen bezoekt Amsterdam jaarlijks ongeveer?', 20, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Bollenstreek kustlijn langs bloembollenvelden (in tientallen km afgerond)?', 3, 'NL'),
    ('Nederlands', 'Hoeveel Friese elfsteden telt de klassieke Elfstedentocht?', 11, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de Elfstedentocht totaal afgerond op tientallen?', 200, 'NL'),
    ('Nederlands', 'Hoeveel keer is de Elfstedentocht in de 20e eeuw geschaatst?', 15, 'NL'),
    ('Nederlands', 'Hoeveel Nederlandse Nobelprijswinnaars zijn er bij benadering (in tientallen afgerond)?', 20, 'NL'),
    ('Nederlands', 'Hoeveel procent van de Nederlanders woont in een rijtjeshuis ongeveer (afgerond op tientallen)?', 30, 'NL'),
    ('Nederlands', 'Hoeveel Nederlandse astronauten zijn er naar de ruimte gevlogen?', 3, 'NL'),
    ('Nederlands', 'Hoeveel kilometer lang is de HSL-Zuid hogesnelheidslijn?', 125, 'NL'),

    # ============ USA (aanvulling op 72 -> ~200) ============
    ('Geografie', 'Hoeveel staten telt de Verenigde Staten?', 50, 'USA'),
    ('Geografie', 'Hoeveel strepen staan er op de Amerikaanse vlag?', 13, 'USA'),
    ('Geografie', 'Hoeveel sterren staan er op de Amerikaanse vlag?', 50, 'USA'),
    ('Geografie', 'Hoeveel staten liggen er op het Noord-Amerikaanse vasteland van de VS (exclusief Alaska en Hawaii)?', 48, 'USA'),
    ('Geografie', 'Hoeveel tijdzones telt het vasteland van de VS?', 4, 'USA'),
    ('Geschiedenis', 'In welk jaar werd de Amerikaanse Onafhankelijkheidsverklaring ondertekend?', 1776, 'USA'),
    ('Geschiedenis', 'Hoeveel presidenten heeft de VS gehad tot en met Joe Biden?', 46, 'USA'),
    ('Geschiedenis', 'Hoeveel jaar duurde de Amerikaanse Burgeroorlog?', 4, 'USA'),
    ('Geschiedenis', 'Hoeveel amendementen bevat de Amerikaanse Grondwet (Bill of Rights meegerekend in de eerste tien)?', 27, 'USA'),
    ('Geschiedenis', 'Hoeveel presidenten werden er vermoord in de Amerikaanse geschiedenis?', 4, 'USA'),
    ('Sport', 'Hoeveel spelers staan er per team op het veld bij American football?', 11, 'USA'),
    ('Sport', 'Hoeveel minuten officiële speeltijd heeft een NFL-wedstrijd?', 60, 'USA'),
    ('Sport', 'Hoeveel spelers staan er per honkbalteam op het veld?', 9, 'USA'),
    ('Sport', 'Hoeveel innings telt een standaard honkbalwedstrijd?', 9, 'USA'),
    ('Sport', 'Hoeveel minuten officiële speeltijd heeft een NBA-wedstrijd?', 48, 'USA'),
    ('Sport', 'Hoeveel teams spelen er in de NFL?', 32, 'USA'),
    ('Sport', 'Hoeveel teams spelen er in de NBA?', 30, 'USA'),
    ('Sport', 'Hoeveel punten levert een touchdown op in American football (met extra point)?', 7, 'USA'),
    ('Sport', 'Hoeveel rings heeft het NBA-logo in het midden?', 1, 'USA'),
    ('Sport', 'Hoeveel Super Bowls won Tom Brady in zijn carrière?', 7, 'USA'),
    ('Sport', 'Hoeveel kuiven heeft een honkbalveld (bases plus home plate)?', 4, 'USA'),
    ('Gebouwen en infrastructuur', 'Hoeveel verdiepingen heeft het Empire State Building?', 102, 'USA'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is het Empire State Building afgerond op tientallen?', 440, 'USA'),
    ('Gebouwen en infrastructuur', 'Hoeveel verdiepingen heeft One World Trade Center?', 104, 'USA'),
    ('Gebouwen en infrastructuur', 'Hoeveel kilometer lang is de Golden Gate Bridge hoofdspanssegment?', 1280, 'USA'),
    ('Gebouwen en infrastructuur', 'Hoeveel kilometer telt de Route 66 bij benadering (in duizenden kilometers afgerond)?', 4, 'USA'),
    ('Gebouwen en infrastructuur', 'Hoeveel kamers heeft het Witte Huis?', 132, 'USA'),
    ('Gebouwen en infrastructuur', 'Hoeveel verdiepingen heeft het Witte Huis?', 4, 'USA'),
    ('Geografie', 'Hoeveel kilometer lang is de Mississippi rivier bij benadering (in duizenden km afgerond)?', 4, 'USA'),
    ('Geografie', 'Hoeveel meter diep is de Grand Canyon op het diepste punt afgerond op honderdtallen?', 1800, 'USA'),
    ('Geografie', 'Hoeveel kilometer lang is de Grand Canyon ongeveer (in honderden km afgerond)?', 400, 'USA'),
    ('Geografie', 'Hoeveel nationale parken telt de VS bij benadering (in tientallen)?', 60, 'USA'),
    ('Geografie', 'Hoeveel van de Grote Meren liggen in de VS en Canada samen?', 5, 'USA'),
    ('Sterrenkunde & ruimte', 'Hoeveel NASA-mannetjes missies naar de maan (Apollo) landden er daadwerkelijk?', 6, 'USA'),
    ('Sterrenkunde & ruimte', 'Hoeveel NASA astronauten liepen er op de maan (alles bij elkaar)?', 12, 'USA'),
    ('Sterrenkunde & ruimte', 'Hoeveel Spaceshuttles bouwde NASA totaal voor orbitale vluchten?', 5, 'USA'),
    ('Sterrenkunde & ruimte', 'Hoeveel dagen duurde de Apollo 11 missie naar de maan en terug afgerond op tientallen?', 10, 'USA'),
    ('Technologie', 'In welk jaar werd Apple opgericht?', 1976, 'USA'),
    ('Technologie', 'In welk jaar werd Microsoft opgericht?', 1975, 'USA'),
    ('Technologie', 'In welk jaar werd Google opgericht?', 1998, 'USA'),
    ('Technologie', 'In welk jaar werd Facebook opgericht?', 2004, 'USA'),
    ('Technologie', 'In welk jaar werd Amazon opgericht?', 1994, 'USA'),
    ('Technologie', 'In welk jaar bracht Apple de eerste iPhone uit?', 2007, 'USA'),
    ('Eten & drinken', 'Hoeveel calorieën bevat een klassieke Amerikaanse Big Mac afgerond op tientallen?', 550, 'USA'),
    ('Eten & drinken', 'Hoeveel ons vlees bevat de klassieke Quarter Pounder?', 4, 'USA'),
    ('Eten & drinken', 'Hoeveel gram suiker zit er in een blikje Coca-Cola van 12 ounce (355 ml) afgerond op tientallen?', 39, 'USA'),
    ('Films en series', 'Hoeveel Oscars won de film Forrest Gump?', 6, 'USA'),
    ('Films en series', 'Hoeveel Star Wars films uit de Skywalker Saga verschenen er?', 9, 'USA'),
    ('Films en series', 'Hoeveel Jurassic Park films verschenen er in totaal?', 6, 'USA'),
    ('Films en series', 'Hoeveel Avengers telde het originele team in de MCU film Avengers (2012)?', 6, 'USA'),
    ('Films en series', 'Hoeveel seizoenen telde de serie Friends?', 10, 'USA'),
    ('Films en series', 'Hoeveel seizoenen telde de serie The Office US?', 9, 'USA'),
    ('Muziek', 'Hoeveel Grammys won Beyoncé in totaal tot 2023?', 32, 'USA'),
    ('Muziek', 'Hoeveel studioalbums bracht Taylor Swift uit tot 2024?', 11, 'USA'),
    ('Muziek', 'Hoeveel nummer 1-hits had The Beatles in de Billboard Hot 100?', 20, 'USA'),
    ('Muziek', 'Hoeveel nummer 1-albums had Elvis Presley in de VS?', 10, 'USA'),
    ('Dieren', 'Hoeveelkg weegt een volwassen Amerikaanse bizon mannetje afgerond op honderdtallen?', 900, 'USA'),
    ('Dieren', 'Hoeveel soorten kolibries komen voor in de VS bij benadering (in tientallen)?', 20, 'USA'),
    ('Politiek en recht', 'Hoeveel rechterzittingen telt het Amerikaanse Hooggerechtshof?', 9, 'USA'),
    ('Politiek en recht', 'Hoeveel jaren duurt een termijn van een Amerikaanse senator?', 6, 'USA'),
    ('Politiek en recht', 'Hoeveel jaren duurt een termijn van een Amerikaanse vertegenwoordiger (House of Representatives)?', 2, 'USA'),
    ('Politiek en recht', 'Hoeveel leden telt het Amerikaanse Huis van Afgevaardigden?', 435, 'USA'),
    ('Politiek en recht', 'Hoeveel leden telt de Amerikaanse Senaat?', 100, 'USA'),
    ('Politiek en recht', 'Hoeveel electorale stemmen heeft Californië (2024)?', 54, 'USA'),
    ('Politiek en recht', 'Hoeveel electorale stemmen zijn er nodig om de VS-presidentsverkiezing te winnen?', 270, 'USA'),
    ('Politiek en recht', 'Hoeveel electorale stemmen heeft Texas (2024)?', 40, 'USA'),
    ('Politiek en recht', 'Hoeveel jaren zit een Amerikaanse president maximaal in twee termijnen?', 8, 'USA'),
    ('Politiek en recht', 'Hoeveel ondertekenaars had de Amerikaanse Onafhankelijkheidsverklaring?', 56, 'USA'),

    # ============ EUROPA (aanvulling op 98 -> ~220) ============
    ('Geografie', 'Hoeveel landen liggen er in Europa bij benadering (in tientallen)?', 50, 'EU'),
    ('Geografie', 'Hoeveel landen zijn lid van de Europese Unie (2024)?', 27, 'EU'),
    ('Geografie', 'Hoeveel landen gebruiken de euro als munt (2024)?', 20, 'EU'),
    ('Geografie', 'Hoeveel officiele talen telt de Europese Unie?', 24, 'EU'),
    ('Geografie', 'Hoeveel Europese landen liggen er niet op het vasteland (exclusief eilanden) in de EU als eilandstaten?', 2, 'EU'),
    ('Geografie', 'Hoeveel meter hoog is de Mont Blanc afgerond op tientallen?', 4800, 'EU'),
    ('Geografie', 'Hoeveel kilometer lang is de Rijn rivier bij benadering (in honderden km afgerond)?', 1300, 'EU'),
    ('Geografie', 'Hoeveel kilometer lang is de Donau rivier bij benadering (in duizenden km afgerond)?', 3, 'EU'),
    ('Geografie', 'Hoeveel landen grenzen aan Duitsland?', 9, 'EU'),
    ('Geografie', 'Hoeveel landen grenzen aan Frankrijk (vasteland excl. overzeese gebieden)?', 8, 'EU'),
    ('Geografie', 'Hoeveel landen grenzen aan Oostenrijk?', 8, 'EU'),
    ('Geografie', 'Hoeveel landen grenzen aan Zwitserland?', 5, 'EU'),
    ('Geografie', 'Hoeveel landen grenzen aan Spanje (vasteland)?', 5, 'EU'),
    ('Geografie', 'Hoeveel landen grenzen aan Polen?', 7, 'EU'),
    ('Geografie', 'Hoeveel officiële talen heeft Zwitserland?', 4, 'EU'),
    ('Geografie', 'Hoeveel officiële talen heeft België?', 3, 'EU'),
    ('Geschiedenis', 'In welk jaar viel de Berlijnse Muur?', 1989, 'EU'),
    ('Geschiedenis', 'In welk jaar eindigde de Eerste Wereldoorlog?', 1918, 'EU'),
    ('Geschiedenis', 'In welk jaar eindigde de Tweede Wereldoorlog in Europa?', 1945, 'EU'),
    ('Geschiedenis', 'In welk jaar begon de Franse Revolutie met de bestorming van de Bastille?', 1789, 'EU'),
    ('Geschiedenis', 'In welk jaar werd de Berlijnse Muur gebouwd?', 1961, 'EU'),
    ('Geschiedenis', 'Hoeveel jaar duurde de Honderdjarige Oorlog tussen Engeland en Frankrijk?', 116, 'EU'),
    ('Geschiedenis', 'Hoeveel jaar duurde de Dertigjarige Oorlog?', 30, 'EU'),
    ('Geschiedenis', 'Hoeveel landen ondertekenden het Verdrag van Rome in 1957?', 6, 'EU'),
    ('Geschiedenis', 'Hoeveel landen waren er bij de oprichting van de NAVO in 1949?', 12, 'EU'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is de Eiffeltoren met antenne?', 330, 'EU'),
    ('Gebouwen en infrastructuur', 'Hoeveel traptreden telt de Eiffeltoren tot de top?', 1665, 'EU'),
    ('Gebouwen en infrastructuur', 'Hoeveel boogsegmenten telt het Colosseum per verdieping?', 80, 'EU'),
    ('Gebouwen en infrastructuur', 'Hoeveel ingangen heeft het Colosseum?', 80, 'EU'),
    ('Gebouwen en infrastructuur', 'Hoeveel torens heeft de Tower Bridge in Londen?', 2, 'EU'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is Big Ben (Elizabeth Tower) afgerond op tientallen?', 100, 'EU'),
    ('Gebouwen en infrastructuur', 'Hoeveel kilometer lang is het Eurotunnel tussen Engeland en Frankrijk onder de zee (in tientallen km)?', 50, 'EU'),
    ('Gebouwen en infrastructuur', 'Hoeveel kamers telt het Paleis van Buckingham?', 775, 'EU'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is het Neuschwanstein Kasteel van buiten afgerond op tientallen?', 60, 'EU'),
    ('Kunst en cultuur', 'Hoeveel sleutelvakken heeft het Leonardo da Vinci werk Laatste Avondmaal in cm hoogte afgerond op tientallen?', 460, 'EU'),
    ('Kunst en cultuur', 'Hoeveel natuursonden (beelden) staan er op Paaseiland - sorry dat zit niet in Europa!', 0, 'EU'),
    ('Filosofie, psychologie en religie', 'Hoeveel geboden bevat de christelijke Tien Geboden lijst?', 10, 'EU'),
    ('Filosofie, psychologie en religie', 'Hoeveel discipelen had Jezus volgens de Bijbel?', 12, 'EU'),
    ('Filosofie, psychologie en religie', 'Hoeveel boeken bevat het Nieuwe Testament bij de protestante telling?', 27, 'EU'),
    ('Filosofie, psychologie en religie', 'Hoeveel zwaarden waren er volgens de legende van koning Arthur beschikbaar?', 1, 'EU'),
    ('Sport', 'Hoeveel landen doen er mee aan de klassieke Europese voetbalkampioenscompetitie (Champions League groepsfase) bij benadering (in tientallen)?', 30, 'EU'),
    ('Sport', 'Hoeveel spelers heeft een rugbyteam per ploeg op het veld (union)?', 15, 'EU'),
    ('Sport', 'Hoeveel minuten duurt een voetbalwedstrijd officieel zonder verlenging?', 90, 'EU'),
    ('Sport', 'Hoeveel games worden er in een Wimbledon-set minimaal gewonnen om de set te pakken?', 6, 'EU'),
    ('Sport', 'Hoeveel keer won Frankrijk de Tour de France bij de mannen tot 2024?', 36, 'EU'),
    ('Sport', 'Hoeveel proloog kilometers telt een Tour de France etappe bijna nooit?', 0, 'EU'),
    ('Eten & drinken', 'Hoeveel soorten kaas produceert Frankrijk officieel bij benadering (in honderdtallen)?', 300, 'EU'),
    ('Eten & drinken', 'Hoeveel landen hebben de Italiaanse pizza Margherita als cultureel erfgoed erkend?', 1, 'EU'),
    ('Eten & drinken', 'Hoeveel liter olijfolie drinkt de gemiddelde Griek per jaar afgerond op tientallen?', 20, 'EU'),
    ('Eten & drinken', 'Hoeveel soorten Duitse worsten kent de Duitse keuken bij benadering (in honderdtallen)?', 300, 'EU'),
    ('Muziek', 'Hoeveel Eurovision Songfestivals won Ierland (2024 stand)?', 7, 'EU'),
    ('Muziek', 'Hoeveel Eurovision Songfestivals won Zweden tot 2024?', 7, 'EU'),
    ('Muziek', 'Hoeveel piano sonates schreef Beethoven bij benadering (in tientallen afgerond)?', 30, 'EU'),
    ('Muziek', 'Hoeveel symfonieën schreef Mozart bij benadering (in tientallen afgerond)?', 40, 'EU'),
    ('Boeken en literatuur', 'Hoeveel delen telt de Harry Potter serie in totaal?', 7, 'EU'),
    ('Boeken en literatuur', 'Hoeveel delen telt de Lord of the Rings trilogie in totaal?', 3, 'EU'),
    ('Boeken en literatuur', 'Hoeveel sonnetten schreef Shakespeare?', 154, 'EU'),
    ('Boeken en literatuur', 'Hoeveel toneelstukken schreef Shakespeare bij benadering (in tientallen afgerond)?', 40, 'EU'),
    ('Boeken en literatuur', 'Hoeveel delen telt de Don Quichot in de volledige moderne editie?', 2, 'EU'),
    ('Films en series', 'Hoeveel James Bond films met Daniel Craig verschenen er?', 5, 'EU'),
    ('Films en series', 'Hoeveel Oscar nominaties kreeg La La Land?', 14, 'EU'),
    ('Films en series', 'Hoeveel delen telt de Harry Potter filmreeks van Warner Bros?', 8, 'EU'),
    ('Politiek en recht', 'Hoeveel landen telt de NAVO (2024)?', 32, 'EU'),
    ('Politiek en recht', 'Hoeveel zetels telt het Europees Parlement (2024-2029)?', 720, 'EU'),
    ('Politiek en recht', 'Hoeveel landen nemen er deel aan de Schengenzone (2024)?', 29, 'EU'),
    ('Politiek en recht', 'Hoeveel leden telt de Raad van Europa (2024) bij benadering (in tientallen)?', 40, 'EU'),
    ('Politiek en recht', 'Hoeveel leden telt de Europese Commissie?', 27, 'EU'),
    ('Politiek en recht', 'Hoeveel rechters telt het Europees Hof voor de Rechten van de Mens?', 46, 'EU'),
    ('Wetenschap', 'In welk jaar werd de Eerste Franse Republiek uitgeroepen (tot science hoort dit niet)?', 1792, 'EU'),

    # ============ AZIË (aanvulling op 68 -> ~200) ============
    ('Geografie', 'Hoeveel landen telt Azië bij benadering (in tientallen)?', 50, 'AZIE'),
    ('Geografie', 'Hoeveel landen grenzen aan China (vasteland excl. zee)?', 14, 'AZIE'),
    ('Geografie', 'Hoeveel landen grenzen aan Rusland (vasteland excl. overzeese)?', 14, 'AZIE'),
    ('Geografie', 'Hoeveel landen grenzen aan India (vasteland)?', 7, 'AZIE'),
    ('Geografie', 'Hoeveel tijdzones telt India als één land?', 1, 'AZIE'),
    ('Geografie', 'Hoeveel officiële talen erkennt India landelijk bij benadering (in tientallen afgerond)?', 20, 'AZIE'),
    ('Geografie', 'Hoeveel eilanden telt Indonesië officieel (2024)?', 17000, 'AZIE'),
    ('Geografie', 'Hoeveel hoofdeilanden heeft Japan (de grote vier)?', 4, 'AZIE'),
    ('Geografie', 'Hoeveel provincies heeft Japan bij benadering (in tientallen)?', 40, 'AZIE'),
    ('Geografie', 'Hoeveel prefecturen heeft Japan?', 47, 'AZIE'),
    ('Geografie', 'Hoeveel provincies heeft China bij benadering (in tientallen)?', 20, 'AZIE'),
    ('Geografie', 'Hoeveel emiraten telt de Verenigde Arabische Emiraten?', 7, 'AZIE'),
    ('Geografie', 'Hoeveel kilometer lang is de Ganges rivier bij benadering (in duizenden km afgerond)?', 3, 'AZIE'),
    ('Geografie', 'Hoeveel meter hoog is Mount Everest?', 8849, 'AZIE'),
    ('Geografie', 'Hoeveel meter hoog is K2 afgerond op honderdtallen?', 8600, 'AZIE'),
    ('Geografie', 'Hoeveel van de 14 bergen boven de 8000 meter liggen in de Himalaya?', 10, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel kilometer lang is de Grote Muur van China officieel gemeten (2024 in duizenden km afgerond)?', 21, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel verdiepingen heeft de Burj Khalifa?', 163, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is de Burj Khalifa afgerond op honderdtallen?', 830, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is de Shanghai Tower afgerond op honderdtallen?', 600, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel verdiepingen heeft de Shanghai Tower?', 128, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel torens heeft de Petronas Twin Towers?', 2, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is de Taj Mahal afgerond op tientallen?', 70, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel minaretten heeft de Taj Mahal?', 4, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel onderdakplekken biedt het Forbidden City in Beijing bij benadering (in honderden kamers)?', 8, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel kamers telt het Forbidden City bij benadering (in honderden)?', 8, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel verdiepingen heeft de Tokyo Skytree uitkijkplatform?', 2, 'AZIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is de Tokyo Tower afgerond op tientallen?', 330, 'AZIE'),
    ('Geschiedenis', 'In welk jaar viel de Berlijnse Muur niet maar werd Japan aangevallen door de VS in Pearl Harbor?', 1941, 'AZIE'),
    ('Geschiedenis', 'In welk jaar eindigde de Tweede Wereldoorlog in Azië met de capitulatie van Japan?', 1945, 'AZIE'),
    ('Geschiedenis', 'In welk jaar werd India onafhankelijk van Groot-Brittannië?', 1947, 'AZIE'),
    ('Geschiedenis', 'In welk jaar werd de Volksrepubliek China gesticht?', 1949, 'AZIE'),
    ('Geschiedenis', 'In welk jaar begon de Koreaanse oorlog?', 1950, 'AZIE'),
    ('Geschiedenis', 'Hoeveel dynastieën telt de Chinese geschiedenis bij benadering (in tientallen afgerond)?', 10, 'AZIE'),
    ('Geschiedenis', 'Hoeveel Wonderen van de Oude Wereld lagen in Azië of Noord-Afrika samen?', 4, 'AZIE'),
    ('Geschiedenis', 'Hoeveel dagen duurde de val van Saigon tot de hereniging (in tientallen dagen afgerond)?', 30, 'AZIE'),
    ('Filosofie, psychologie en religie', 'Hoeveel boeken bevat de Koran?', 114, 'AZIE'),
    ('Filosofie, psychologie en religie', 'Hoeveel soera s telt de Koran?', 114, 'AZIE'),
    ('Filosofie, psychologie en religie', 'Hoeveel procent van de wereldbevolking is boeddhistisch bij benadering (in tientallen procenten)?', 10, 'AZIE'),
    ('Filosofie, psychologie en religie', 'Hoeveel paden telt het Achtvoudige Pad van het boeddhisme?', 8, 'AZIE'),
    ('Filosofie, psychologie en religie', 'Hoeveel edelwaarheden kent het boeddhisme?', 4, 'AZIE'),
    ('Filosofie, psychologie en religie', 'Hoeveel avatars heeft Vishnu volgens de Hindoe traditie?', 10, 'AZIE'),
    ('Filosofie, psychologie en religie', 'Hoeveel keer per dag bidden moslims volgens de vijf pilaren van de islam?', 5, 'AZIE'),
    ('Filosofie, psychologie en religie', 'Hoeveel dagen duurt de Ramadan per jaar (maanmaand afgerond op tientallen)?', 30, 'AZIE'),
    ('Filosofie, psychologie en religie', 'Hoeveel pelgrims bezoeken Mekka jaarlijks bij benadering (in miljoenen)?', 2, 'AZIE'),
    ('Eten & drinken', 'Hoeveel soorten sushi wordt er klassiek onderscheiden in Japan (hoofdtypes)?', 5, 'AZIE'),
    ('Eten & drinken', 'Hoeveel calorieën bevat een portie Pad Thai afgerond op tientallen?', 700, 'AZIE'),
    ('Eten & drinken', 'Hoeveel kruiden bevat de klassieke Chinese Five-Spice?', 5, 'AZIE'),
    ('Eten & drinken', 'Hoeveel soorten curry bevat de Indiase keuken bij benadering (in tientallen)?', 30, 'AZIE'),
    ('Muziek', 'Hoeveel snaarinstrumenten bevat de klassieke Japanse koto-ensemble van hoort?', 13, 'AZIE'),
    ('Muziek', 'Hoeveel snaren heeft een klassieke Japanse koto?', 13, 'AZIE'),
    ('Muziek', 'Hoeveel snaren heeft de Indiase sitar bij benadering (in tientallen)?', 20, 'AZIE'),
    ('Muziek', 'Hoeveel snaren heeft de klassieke Chinese guzheng bij benadering (in tientallen)?', 20, 'AZIE'),
    ('Dieren', 'Hoeveel vlekken heeft een klassieke Bengaalse tijger bij benadering (in tientallen)?', 100, 'AZIE'),
    ('Dieren', 'Hoeveel kilogram weegt een volwassen Aziatische olifant afgerond op duizendtallen?', 4000, 'AZIE'),
    ('Dieren', 'Hoeveel kilogram weegt een volwassen Bengaalse tijger afgerond op honderdtallen?', 200, 'AZIE'),
    ('Dieren', 'Hoeveel soorten dieren bevat de Chinese zodiac?', 12, 'AZIE'),
    ('Dieren', 'Hoeveel pagodavormige heuvels heeft de klassieke Chinese berg Huangshan bij benadering (in tientallen pieken)?', 70, 'AZIE'),
    ('Sterrenkunde & ruimte', 'Hoeveel maanmissies naar de maan (Chang e-programma) lanceerde China?', 6, 'AZIE'),
    ('Sterrenkunde & ruimte', 'Hoeveel satellieten lanceerde India in één enkele raket als record (2017)?', 104, 'AZIE'),
    ('Technologie', 'In welk jaar werd de Toyota motorfiets eerste gebouwd - nee Toyota is auto (1885 Daimler - dit zit niet in Azië)?', 0, 'AZIE'),
    ('Technologie', 'In welk jaar werd Sony opgericht?', 1946, 'AZIE'),
    ('Technologie', 'In welk jaar werd Samsung opgericht?', 1938, 'AZIE'),
    ('Technologie', 'In welk jaar werd Toyota opgericht als automerk?', 1937, 'AZIE'),
    ('Technologie', 'In welk jaar lanceerde Japan de Shinkansen hogesnelheidstrein?', 1964, 'AZIE'),
    ('Technologie', 'Hoeveel kilometer per uur rijdt de Shanghai Maglev trein (afgerond op tientallen)?', 430, 'AZIE'),
    ('Politiek en recht', 'Hoeveel leden telt de ASEAN-organisatie (2024)?', 10, 'AZIE'),
    ('Politiek en recht', 'Hoeveel leden telt de SAARC organisatie?', 8, 'AZIE'),
    ('Politiek en recht', 'Hoeveel provincies heeft Indonesië (2024)?', 38, 'AZIE'),
    ('Politiek en recht', 'Hoeveel emiraten heeft Saoedi-Arabië als koninkrijk in bestuurlijke regio (provincies)?', 13, 'AZIE'),
    ('Politiek en recht', 'Hoeveel Chinezen wonen er in China bij benadering (in miljarden afgerond op halve)?', 1, 'AZIE'),
    ('Politiek en recht', 'Hoeveel Indiërs wonen er in India bij benadering (in miljarden)?', 1, 'AZIE'),

    # ============ AFRIKA (aanvulling op 15 -> ~130) ============
    ('Geografie', 'Hoeveel landen telt Afrika (2024)?', 54, 'AFRIKA'),
    ('Geografie', 'Hoeveel landen liggen er aan de Middellandse Zee (Noord-Afrika + Europa + Azië)?', 22, 'AFRIKA'),
    ('Geografie', 'Hoeveel Afrikaanse landen grenzen aan de Middellandse Zee?', 6, 'AFRIKA'),
    ('Geografie', 'Hoeveel Afrikaanse landen grenzen aan de Atlantische Oceaan bij benadering (in tientallen afgerond)?', 20, 'AFRIKA'),
    ('Geografie', 'Hoeveel kilometer lang is de Nijl rivier bij benadering (in duizenden km afgerond)?', 7, 'AFRIKA'),
    ('Geografie', 'Hoeveel landen heeft de Nijl als bron of doorstroom bij benadering (in tientallen afgerond)?', 10, 'AFRIKA'),
    ('Geografie', 'Hoeveel vierkante kilometer beslaat de Sahara bij benadering (in miljoenen km² afgerond)?', 9, 'AFRIKA'),
    ('Geografie', 'Hoeveel landen heeft de Sahara deels in zijn gebied bij benadering (in tientallen afgerond)?', 10, 'AFRIKA'),
    ('Geografie', 'Hoeveel meter hoog is de Kilimanjaro (Uhuru Peak) afgerond op honderdtallen?', 5900, 'AFRIKA'),
    ('Geografie', 'Hoeveel kilometer lang is de Kalahari woestijn bij benadering (in honderden km afgerond)?', 900, 'AFRIKA'),
    ('Geografie', 'Hoeveel landen telt de Sahel-regio bij benadering (in tientallen afgerond)?', 10, 'AFRIKA'),
    ('Geografie', 'Hoeveel eilandstaten telt Afrika?', 6, 'AFRIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is de Grote Piramide van Gizeh afgerond op tientallen?', 140, 'AFRIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is de Toren van Caïro (Cairo Tower) afgerond op tientallen?', 190, 'AFRIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel piramides telt het piramideveld van Gizeh (de drie grote)?', 3, 'AFRIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel bekende piramides telt Egypte in totaal bij benadering (in tientallen afgerond)?', 120, 'AFRIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel kilometer lang is de Suezkanaal (in tientallen km afgerond)?', 190, 'AFRIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel jaar duurde de bouw van de Grote Sfinx bij benadering (in tientallen jaar afgerond)?', 20, 'AFRIKA'),
    ('Geschiedenis', 'In welk jaar werd Nelson Mandela vrijgelaten uit de gevangenis?', 1990, 'AFRIKA'),
    ('Geschiedenis', 'In welk jaar werd Zuid-Afrika officieel anti-apartheid democratie met Mandela als president?', 1994, 'AFRIKA'),
    ('Geschiedenis', 'In welk jaar werd Egypte officieel onafhankelijk van Groot-Brittannië?', 1922, 'AFRIKA'),
    ('Geschiedenis', 'In welk jaar viel Carthago aan de Romeinen tijdens de Derde Punische Oorlog?', 146, 'AFRIKA'),
    ('Geschiedenis', 'Hoeveel jaar duurde de apartheid in Zuid-Afrika (1948-1994)?', 46, 'AFRIKA'),
    ('Geschiedenis', 'Hoeveel Wonderen van de Oude Wereld stonden er in Egypte?', 1, 'AFRIKA'),
    ('Geschiedenis', 'Hoeveel jaar regeerde Cleopatra VII bij benadering (in tientallen jaar afgerond)?', 20, 'AFRIKA'),
    ('Dieren', 'Hoeveel dieren bevat de klassieke Big Five van Afrika?', 5, 'AFRIKA'),
    ('Dieren', 'Hoeveel kilometer per uur kan een cheetah sprinten (afgerond op tientallen)?', 110, 'AFRIKA'),
    ('Dieren', 'Hoeveel kilogram weegt een volwassen Afrikaanse olifant mannetje afgerond op duizendtallen?', 6000, 'AFRIKA'),
    ('Dieren', 'Hoeveel kilogram weegt een volwassen Nijlpaard afgerond op honderdtallen?', 1500, 'AFRIKA'),
    ('Dieren', 'Hoeveel meter lang kan een volwassen Nijlkrokodil worden afgerond op halve meters?', 5, 'AFRIKA'),
    ('Dieren', 'Hoeveel procent van de leeuwenpopulatie leeft in Sub-Sahara Afrika (afgerond op tientallen)?', 90, 'AFRIKA'),
    ('Dieren', 'Hoeveel bijenkorven producert de gemiddelde Ethiopische bijenhouder per jaar?', 0, 'AFRIKA'),
    ('Natuurverschijnselen', 'Hoeveel meter hoog is de Victoriawatervallen afgerond op tientallen?', 110, 'AFRIKA'),
    ('Natuurverschijnselen', 'Hoeveel meter breed is de Victoriawatervallen bij benadering (in honderden meters afgerond)?', 1700, 'AFRIKA'),
    ('Milieu en duurzaamheid', 'Hoeveel procent van de Sahara was ooit groen tijdens de Groene Sahara periode (afgerond op tientallen)?', 100, 'AFRIKA'),
    ('Eten & drinken', 'Hoeveel landen produceren koffie in Afrika bij benadering (in tientallen afgerond)?', 30, 'AFRIKA'),
    ('Eten & drinken', 'Hoeveel kilogram koffie produceert Ethiopië jaarlijks bij benadering (in miljoenen kilogram afgerond op honderdtallen)?', 400, 'AFRIKA'),
    ('Muziek', 'Hoeveel snaren heeft de West-Afrikaanse kora bij benadering (in tientallen)?', 20, 'AFRIKA'),
    ('Muziek', 'Hoeveel snaren heeft de klassieke Afrikaanse kora traditioneel?', 21, 'AFRIKA'),
    ('Muziek', 'Hoeveel snaren heeft de West-Afrikaanse djembé als trommel?', 0, 'AFRIKA'),
    ('Politiek en recht', 'Hoeveel landen zijn lid van de Afrikaanse Unie (2024)?', 55, 'AFRIKA'),
    ('Politiek en recht', 'Hoeveel landen gebruiken de West-Afrikaanse CFA frank bij benadering (in tientallen afgerond)?', 10, 'AFRIKA'),
    ('Politiek en recht', 'Hoeveel landen gebruiken de Centraal-Afrikaanse CFA frank?', 6, 'AFRIKA'),

    # ============ OCEANIË (aanvulling op 12 -> ~120) ============
    ('Geografie', 'Hoeveel staten heeft Australië?', 6, 'OCEANIE'),
    ('Geografie', 'Hoeveel territoria heeft Australië naast de staten?', 2, 'OCEANIE'),
    ('Geografie', 'Hoeveel provincies heeft Nieuw-Zeeland bij benadering (in tientallen afgerond - regions)?', 20, 'OCEANIE'),
    ('Geografie', 'Hoeveel hoofdeilanden heeft Nieuw-Zeeland?', 2, 'OCEANIE'),
    ('Geografie', 'Hoeveel kilometer lang is de Great Barrier Reef bij benadering (in duizenden km afgerond)?', 2, 'OCEANIE'),
    ('Geografie', 'Hoeveel eilanden telt het Great Barrier Reef bij benadering (in honderden afgerond)?', 900, 'OCEANIE'),
    ('Geografie', 'Hoeveel eilanden heeft Fiji bij benadering (in honderden afgerond)?', 300, 'OCEANIE'),
    ('Geografie', 'Hoeveel eilanden heeft Papoea-Nieuw-Guinea bij benadering (in honderden afgerond)?', 600, 'OCEANIE'),
    ('Geografie', 'Hoeveel meter hoog is Mount Cook (Aoraki) afgerond op honderdtallen?', 3700, 'OCEANIE'),
    ('Geografie', 'Hoeveel meter hoog is Uluru (Ayers Rock) afgerond op tientallen?', 350, 'OCEANIE'),
    ('Geografie', 'Hoeveel nationale parken telt Australië bij benadering (in honderden afgerond)?', 500, 'OCEANIE'),
    ('Geografie', 'Hoeveel kilometer lang is de Australische kustlijn bij benadering (in duizenden km afgerond)?', 50, 'OCEANIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel schelpvormige panelen bedekken het dak van de Sydney Opera House bij benadering (in miljoenen)?', 1, 'OCEANIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel verdiepingen heeft de Q1 Tower in Gold Coast (tallest in Australië)?', 78, 'OCEANIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel boogpartijen heeft de Sydney Harbour Bridge?', 1, 'OCEANIE'),
    ('Gebouwen en infrastructuur', 'Hoeveel rivieren bruggen telt Sydney Harbour?', 0, 'OCEANIE'),
    ('Dieren', 'Hoeveel buideldierensoorten bevat de klassieke Australische megafauna lijst bij benadering (in tientallen)?', 20, 'OCEANIE'),
    ('Dieren', 'Hoeveel kg weegt een volwassen mannelijke kangoeroe afgerond op tientallen?', 90, 'OCEANIE'),
    ('Dieren', 'Hoeveel uur per dag slaapt een koala bij benadering (in tientallen uur afgerond)?', 20, 'OCEANIE'),
    ('Dieren', 'Hoeveel soorten kangoeroes bevat de macropod-familie bij benadering (in tientallen afgerond)?', 50, 'OCEANIE'),
    ('Dieren', 'Hoeveel cm lang wordt een volwassen emoe vrouwtje bij benadering (in tientallen cm)?', 150, 'OCEANIE'),
    ('Dieren', 'Hoeveel giftige spinnensoorten kent Australië bij benadering (in tientallen afgerond)?', 40, 'OCEANIE'),
    ('Dieren', 'Hoeveel van de 10 giftigste slangen ter wereld komen voor in Australië?', 0, 'OCEANIE'),
    ('Sport', 'Hoeveel keer won Nieuw-Zeeland de Rugby World Cup bij de mannen tot 2023?', 3, 'OCEANIE'),
    ('Sport', 'Hoeveel keer won Australië de Rugby World Cup bij de mannen tot 2023?', 2, 'OCEANIE'),
    ('Sport', 'Hoeveel spelers staat er per ploeg op het veld bij een rugby league-wedstrijd?', 13, 'OCEANIE'),
    ('Sport', 'Hoeveel punten levert een try op in rugby union?', 5, 'OCEANIE'),
    ('Sport', 'Hoeveel Australische Open titels won Novak Djokovic tot 2024?', 10, 'OCEANIE'),
    ('Sport', 'Hoeveel dagen duurt de Tour Down Under wielrennen?', 6, 'OCEANIE'),
    ('Muziek', 'Hoeveel Grammy won de Australische band AC/DC bij benadering (in tientallen afgerond)?', 0, 'OCEANIE'),
    ('Muziek', 'Hoeveel albums bracht AC/DC uit tot 2024 (studioalbums)?', 17, 'OCEANIE'),
    ('Muziek', 'Hoeveel albums bracht de Australische band Midnight Oil uit bij benadering (in tientallen afgerond)?', 10, 'OCEANIE'),
    ('Films en series', 'Hoeveel Oscars won de film Mad Max Fury Road?', 6, 'OCEANIE'),
    ('Films en series', 'Hoeveel Mad Max films zijn er in totaal gemaakt?', 5, 'OCEANIE'),
    ('Films en series', 'Hoeveel uur duurt de film Avatar: The Way of Water bij benadering (in hele uren afgerond)?', 3, 'OCEANIE'),
    ('Politiek en recht', 'Hoeveel zetels telt het Australische Huis van Afgevaardigden (House of Representatives) bij benadering (in tientallen afgerond)?', 150, 'OCEANIE'),
    ('Politiek en recht', 'Hoeveel zetels telt de Nieuw-Zeelandse Kamer van Afgevaardigden?', 120, 'OCEANIE'),
    ('Politiek en recht', 'Hoeveel landen telt Oceanië bij benadering (in tientallen afgerond)?', 10, 'OCEANIE'),
    ('Politiek en recht', 'Hoeveel landen telt het Pacific Islands Forum bij benadering (in tientallen afgerond)?', 20, 'OCEANIE'),

    # ============ LATIJNS-AMERIKA (aanvulling op 17 -> ~120) ============
    ('Geografie', 'Hoeveel landen telt Zuid-Amerika (2024)?', 12, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel landen telt Midden-Amerika (inclusief Mexico bij sommige tellingen) bij benadering (in tientallen afgerond)?', 10, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel landen grenzen aan Brazilië?', 10, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel landen grenzen aan Peru?', 5, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel landen grenzen aan Colombia?', 5, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel landen grenzen aan Argentinië?', 5, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel kilometer lang is de Amazone rivier bij benadering (in duizenden km afgerond)?', 7, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel landen deelt het Amazonebekken bij benadering (in tientallen afgerond)?', 10, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel vierkante kilometer beslaat het Amazone regenwoud bij benadering (in miljoenen km² afgerond)?', 6, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel kilometer lang is de Andes bergketen bij benadering (in duizenden km afgerond)?', 7, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel landen deelt de Andes bergketen bij benadering (in tientallen afgerond)?', 10, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel meter hoog is de Aconcagua (hoogste piek van de Andes en buiten-Azië) afgerond op honderdtallen?', 7000, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel meter hoog is de Angel Falls (Salto Angel) afgerond op honderdtallen?', 900, 'LATIJNS_AMERIKA'),
    ('Geografie', 'Hoeveel meter hoog is de Titicaca meer boven zeeniveau afgerond op honderdtallen?', 3800, 'LATIJNS_AMERIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter lang is het Panamakanaal (in tientallen km afgerond)?', 80, 'LATIJNS_AMERIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel sluizen heeft het Panamakanaal bij benadering (in tientallen afgerond)?', 10, 'LATIJNS_AMERIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel kilometer lang is de Metro van Mexico-Stad netwerk bij benadering (in honderden km afgerond)?', 200, 'LATIJNS_AMERIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel verdiepingen heeft de Gran Torre Santiago in Chili (tallest in Latijns-Amerika)?', 62, 'LATIJNS_AMERIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel verdiepingen heeft het woontoren BD Bacatá in Bogotá bij benadering (in tientallen afgerond)?', 60, 'LATIJNS_AMERIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel kilometer lang is de Christus Redentor standbeeld hoogte in meters afgerond op tientallen?', 40, 'LATIJNS_AMERIKA'),
    ('Gebouwen en infrastructuur', 'Hoeveel meter hoog is de Christus Redentor standbeeld (met sokkel)?', 40, 'LATIJNS_AMERIKA'),
    ('Geschiedenis', 'In welk year ontdekte Columbus Amerika (de eerste reis)?', 1492, 'LATIJNS_AMERIKA'),
    ('Geschiedenis', 'In welk jaar viel het Azteekse rijk aan de Spanjaarden onder Cortés?', 1521, 'LATIJNS_AMERIKA'),
    ('Geschiedenis', 'In welk jaar viel het Inca-rijk aan de Spanjaarden onder Pizarro?', 1533, 'LATIJNS_AMERIKA'),
    ('Geschiedenis', 'In welk jaar werd Brazilië officieel onafhankelijk van Portugal?', 1822, 'LATIJNS_AMERIKA'),
    ('Geschiedenis', 'Hoeveel jaar duurde de rubberboom-crisis in de Amazone bij benadering (in tientallen jaar afgerond)?', 40, 'LATIJNS_AMERIKA'),
    ('Dieren', 'Hoeveel soorten vogels telt de Amazone bij benadering (in honderden afgerond)?', 1300, 'LATIJNS_AMERIKA'),
    ('Dieren', 'Hoeveel soorten dieren telt het Amazone regenwoud bij benadering (in miljoenen - schatting afgerond op tientallen van miljoenen)?', 10, 'LATIJNS_AMERIKA'),
    ('Dieren', 'Hoeveel kilogram weegt een volwassen jaguar mannetje afgerond op tientallen?', 100, 'LATIJNS_AMERIKA'),
    ('Dieren', 'Hoeveel meter lang kan een groene anaconda worden afgerond op hele meters?', 6, 'LATIJNS_AMERIKA'),
    ('Dieren', 'Hoeveel soorten apen telt het Amazonegebied bij benadering (in tientallen afgerond)?', 100, 'LATIJNS_AMERIKA'),
    ('Eten & drinken', 'Hoeveel kilogram koffie produceert Brazilië jaarlijks bij benadering (in miljoenen zakken afgerond op tientallen)?', 60, 'LATIJNS_AMERIKA'),
    ('Eten & drinken', 'Hoeveel procent van de wereldkoffie wordt geproduceerd door Brazilië (afgerond op tientallen)?', 30, 'LATIJNS_AMERIKA'),
    ('Eten & drinken', 'Hoeveel liter mate theedrinkt de gemiddelde Argentijn per jaar bij benadering (in tientallen liters)?', 50, 'LATIJNS_AMERIKA'),
    ('Eten & drinken', 'Hoeveel kilogram rundvlees eet de gemiddelde Argentijn per jaar bij benadering (in tientallen kg afgerond)?', 50, 'LATIJNS_AMERIKA'),
    ('Muziek', 'Hoeveel snaren heeft de klassieke Mexicaanse mariachi-gitarron (bajo sexto)?', 12, 'LATIJNS_AMERIKA'),
    ('Muziek', 'Hoeveel muzikanten heeft een klassieke mariachi band bij benadering (in tientallen afgerond)?', 10, 'LATIJNS_AMERIKA'),
    ('Muziek', 'Hoeveel dansstijlen worden er klassiek onderscheiden in de Cubaanse rumba-familie (drie hoofdstijlen)?', 3, 'LATIJNS_AMERIKA'),
    ('Sport', 'Hoeveel keer won Brazilië de FIFA World Cup voetbal bij de mannen (2024)?', 5, 'LATIJNS_AMERIKA'),
    ('Sport', 'Hoeveel keer won Argentinië de FIFA World Cup voetbal bij de mannen (2024)?', 3, 'LATIJNS_AMERIKA'),
    ('Sport', 'Hoeveel keer won Uruguay de FIFA World Cup voetbal bij de mannen?', 2, 'LATIJNS_AMERIKA'),
    ('Sport', 'Hoeveel Copa América titels won Argentinië tot 2024?', 16, 'LATIJNS_AMERIKA'),
    ('Sport', 'Hoeveel keer was Brazilië gastheer van de FIFA World Cup?', 2, 'LATIJNS_AMERIKA'),
    ('Politiek en recht', 'Hoeveel staten heeft Brazilië?', 26, 'LATIJNS_AMERIKA'),
    ('Politiek en recht', 'Hoeveel staten heeft Mexico?', 32, 'LATIJNS_AMERIKA'),
    ('Politiek en recht', 'Hoeveel provincies heeft Argentinië (inclusief de hoofdstad als aparte provincie)?', 24, 'LATIJNS_AMERIKA'),
    ('Politiek en recht', 'Hoeveel leden telt de Mercosur handelsblok als volwaardige leden?', 4, 'LATIJNS_AMERIKA'),
    ('Politiek en recht', 'Hoeveel landen telt de CELAC organisatie bij benadering (in tientallen afgerond)?', 30, 'LATIJNS_AMERIKA'),
]

if __name__ == '__main__':
    from collections import Counter
    c = Counter(r[3] for r in NIEUWE_VRAGEN)
    print('Nieuwe vragen per regio:', dict(c))
    print('Totaal:', len(NIEUWE_VRAGEN))
