# -*- coding: utf-8 -*-
"""Netto — de 212 vragen met afrondtaal uit de reservevoorraad, opgeschoond.

WAAROM DE RESERVE ERTOE DOET
Deze vragen zitten in geen enkele puzzel, dus een speler ziet ze vandaag niet.
Toch zijn ze het opschonen waard: voor multiplayer en als achtervang voor de
daily wil je een grote voorraad vragen die niemand al gespeeld heeft. Een
voorraad vol "afgerond op tientallen" is daarvoor onbruikbaar.

WAT ER MET ZO'N VRAAG GEBEURT
De formulering gaat er altijd uit — "afgerond op tientallen" verraadt de orde
van grootte en het spel rondt zelf al af. Het antwoord verscherp ik alleen waar
ik de echte waarde kan verantwoorden. Bij de Tokyo Tower staat 330 met "afgerond
op tientallen"; die is 333 meter, dus dat wordt de vraag. Bij "hoeveel soorten
apen telt het Amazonegebied" bestaat geen exact getal, dus daar blijft de ronde
waarde staan en verdwijnt alleen de lelijke formulering.

STATUSSEN
  exact       Vraag herschreven én het antwoord aangescherpt naar de echte waarde.
  opschonen   Alleen de formulering aangepast; het antwoord blijft zoals het was,
              omdat er geen preciezer getal te verantwoorden is.
  fout        Het opgegeven antwoord klopt niet. Nieuw antwoord erbij.
  schrappen   Onbruikbaar: onverifieerbaar, onleesbaar, of een duplicaat van een
              vraag die al in het spel zit.
"""

# Nr: (status, nieuwe vraag of None, nieuw antwoord of None, toelichting)
CORRECTIES = {
    # ---------------- Dieren ----------------
    627: ('exact', 'Hoeveel toneelstukken schreef Shakespeare volgens de gangbare telling?', 39, 'De traditionele canon telt 39 stukken.'),
    634: ('schrappen', None, None, 'Er bestaat geen vaste "lijst Australische megafauna" met een telbaar aantal.'),
    635: ('opschonen', 'Hoeveel centimeter hoog wordt een volwassen emoe?', 170, 'Emoes worden 150 tot 190 cm; 170 is het midden.'),
    640: ('schrappen', None, None, 'Het aantal giftige spinnensoorten in Australië is nergens hard vastgelegd.'),
    643: ('exact', 'Hoeveel kilogram weegt een volwassen mannelijke rode reuzenkangoeroe maximaal?', 90, None),
    645: ('opschonen', 'Hoeveel kilogram weegt een volwassen mannetjesolifant in Afrika?', 6000, None),
    646: ('opschonen', 'Hoeveel kilogram weegt een volwassen Aziatische olifant?', 4000, None),
    647: ('exact', 'Hoeveel kilogram weegt een volwassen mannelijke Bengaalse tijger?', 220, 'Mannetjes wegen 200 tot 240 kg.'),
    648: ('opschonen', 'Hoeveel kilogram weegt een volwassen nijlpaard?', 1500, None),
    649: ('exact', 'Hoeveel kilogram weegt een volwassen emoe?', 45, 'Emoes wegen 40 tot 45 kg, niet 50.'),
    650: ('opschonen', 'Hoeveel kilogram weegt een volwassen giraffe?', 1200, None),
    651: ('opschonen', 'Hoeveel kilogram weegt een volwassen mannelijke jaguar?', 100, None),
    652: ('opschonen', 'Hoeveel kilogram weegt een volwassen witte neushoorn?', 2000, None),
    653: ('opschonen', 'Hoeveel kilogram weegt een volwassen wombat?', 30, None),
    655: ('exact', 'Hoeveel kilometer per uur haalt een cheetah op zijn snelst?', 110, None),
    656: ('opschonen', 'Hoeveel kilometer per uur sprint een jaguar?', 80, None),
    657: ('opschonen', 'Hoeveel kilometer per uur sprint een leeuw?', 80, None),
    661: ('opschonen', 'Hoeveel meter lang kan een groene anaconda worden?', 6, None),
    662: ('opschonen', 'Hoeveel meter lang kan een volwassen nijlkrokodil worden?', 5, None),
    663: ('opschonen', 'Hoeveel meter lang wordt een Afrikaanse olifant?', 7, None),
    664: ('opschonen', 'Hoeveel meter lang wordt een zoutwaterkrokodil maximaal?', 6, None),
    667: ('schrappen', None, None, '"Pagodavormige heuvels" is geen bestaand telbaar kenmerk van Huangshan.'),
    671: ('exact', 'Hoeveel procent van de wilde leeuwen leeft in Sub-Sahara Afrika?', 95, 'Vrijwel de hele populatie; alleen in India leeft nog een kleine groep.'),
    672: ('opschonen', 'Hoeveel apensoorten telt het Amazonegebied ongeveer?', 100, None),
    674: ('schrappen', None, None, 'Eenheden lopen door elkaar: "in miljoenen, afgerond op tientallen van miljoenen".'),
    675: ('exact', 'Hoeveel soorten telt de kangoeroefamilie (Macropodidae)?', 65, None),
    676: ('opschonen', 'Hoeveel kolibriesoorten komen voor in de Verenigde Staten?', 20, None),
    677: ('opschonen', 'Hoeveel lemuursoorten telt Madagaskar ongeveer?', 100, None),
    678: ('exact', 'Hoeveel vogelsoorten telt Australië?', 830, None),
    679: ('opschonen', 'Hoeveel vogelsoorten telt Colombia, het land met de meeste ter wereld?', 1900, None),
    680: ('opschonen', 'Hoeveel vogelsoorten telt het Amazonegebied?', 1300, None),
    686: ('exact', 'Hoeveel uur per dag slaapt een koala?', 20, None),
    689: ('schrappen', None, None, 'Feitelijk onjuist: een tijger heeft strepen, geen vlekken.'),
    690: ('opschonen', 'Hoeveel kilogram weegt een volwassen mannelijke Amerikaanse bizon?', 900, None),
    691: ('opschonen', 'Hoeveel ton weegt een volwassen blauwe vinvis?', 150, None),

    # ---------------- Eten en drinken ----------------
    704: ('schrappen', None, None, 'Duplicaat van vraag 13, die al in een daily zit.'),
    705: ('schrappen', None, None, 'Een portie Pad Thai heeft geen vaste calorische waarde.'),
    707: ('exact', 'Hoeveel gram suiker zit er in een Amerikaans blikje Coca-Cola van 355 ml?', 39,
          'Precies het geval waar de afrondformulering onzin was: het antwoord is gewoon 39.'),
    710: ('opschonen', 'Hoeveel miljoen zakken koffie produceert Brazilië per jaar?', 60, None),
    711: ('schrappen', None, None, 'Eenheden spreken elkaar tegen: "kilogram ... in miljoenen kilogram".'),
    712: ('opschonen', 'Hoeveel kilogram rundvlees eet een Argentijn per jaar?', 50, None),
    715: ('opschonen', 'Hoeveel Afrikaanse landen produceren koffie?', 30, None),
    716: ('schrappen', None, None, 'Mateverbruik wordt in kilogram bladeren gemeten, niet in liters.'),
    717: ('schrappen', None, None, 'Zelfde probleem als 716, en bovendien een bijna-duplicaat daarvan.'),
    718: ('opschonen', 'Hoeveel liter olijfolie gebruikt een Griek per jaar?', 20, None),
    721: ('exact', 'Hoeveel procent van de wereldcacao komt uit West-Afrika?', 70, None),
    722: ('exact', 'Hoeveel procent van de wereldkoffie komt uit Brazilië?', 35, 'Brazilië levert ongeveer een derde, niet 30.'),
    723: ('opschonen', 'Hoeveel soorten worst kent de Duitse keuken ongeveer?', 300, None),
    724: ('schrappen', None, None, 'Het aantal Indiase curry-soorten is niet vastgelegd.'),
    725: ('opschonen', 'Hoeveel kaassoorten produceert Frankrijk ongeveer?', 300, None),

    # ---------------- Cultuur en religie ----------------
    747: ('exact', 'Hoeveel minuten duurt de film Avatar: The Way of Water?', 192, 'Drie uur en twaalf minuten.'),
    755: ('exact', 'Hoeveel dagen duurt de Ramadan maximaal?', 30, 'Een maanmaand telt 29 of 30 dagen.'),
    766: ('opschonen', 'Hoeveel miljoen pelgrims bezoeken Mekka jaarlijks?', 2, None),
    767: ('exact', 'Hoeveel procent van de wereldbevolking is boeddhistisch?', 7, 'Ongeveer 7 procent, niet 10.'),

    # ---------------- Bouwwerken ----------------
    770: ('opschonen', 'Hoeveel piramides telt Egypte ongeveer?', 120, None),
    775: ('schrappen', None, None, 'De bouwduur van de Sfinx is onbekend.'),
    777: ('schrappen', None, None, 'Vraagt kilometers maar wil de hoogte in meters.'),
    779: ('exact', 'Hoeveel kilometer lang is de Grote Muur van China volgens de officiële meting?', 21196, None),
    780: ('exact', 'Hoeveel kilometer lang is het metronet van Mexico-Stad?', 226, None),
    781: ('exact', 'Hoeveel kilometer lang is het Suezkanaal?', 193, None),
    782: ('exact', 'Hoeveel kilometer van de Kanaaltunnel ligt onder zee?', 38, 'De tunnel is 50 km; 38 km ligt onder water.'),
    784: ('exact', 'Hoeveel kilometer lang was Route 66?', 3945, None),
    786: ('exact', 'Hoeveel meter hoog is de Elizabeth Tower, de toren van Big Ben?', 96, None),
    787: ('exact', 'Hoeveel meter hoog is het Christus Verlosser-beeld zonder sokkel?', 30, 'Het beeld is 30 m, met sokkel 38 m.'),
    788: ('schrappen', None, None, 'Duplicaat van vraag 43, die al in een daily zit.'),
    792: ('exact', 'Hoeveel meter hoog is de Grote Piramide van Gizeh nu?', 139, 'Oorspronkelijk 147 m; door erosie nu 138,5.'),
    794: ('exact', 'Hoeveel meter hoog is de Shanghai Tower?', 632, None),
    796: ('exact', 'Hoeveel meter hoog is de Sydney Tower?', 309, None),
    797: ('exact', 'Hoeveel meter hoog is de Taj Mahal?', 73, None),
    798: ('exact', 'Hoeveel meter hoog is de Tokyo Tower?', 333, None),
    799: ('exact', 'Hoeveel meter hoog is de Cairo Tower?', 187, None),
    800: ('schrappen', None, None, 'Duplicaat van vraag 232.'),
    801: ('exact', 'Hoeveel meter hoog is kasteel Neuschwanstein?', 65, None),
    804: ('schrappen', None, None, 'Vraagt meters maar wil kilometers, en duplicaat van vraag 29.'),
    805: ('schrappen', None, None, '"Onderdakplekken ... in honderden kamers" is onleesbaar.'),
    809: ('schrappen', None, None, 'Duplicaat van vraag 816, en de eenheid klopt niet.'),
    811: ('exact', 'Hoeveel sluizen heeft het Panamakanaal?', 12, 'Zes sluizenparen.'),
    827: ('exact', 'Hoeveel verdiepingen heeft de BD Bacatá in Bogotá?', 67, None),

    # ---------------- Geografie ----------------
    834: ('exact', 'Hoeveel Afrikaanse landen grenzen aan de Atlantische Oceaan?', 23, None),
    839: ('schrappen', None, None, 'Duplicaat van vraag 307.'),
    840: ('exact', 'Hoeveel eilanden telt Fiji?', 332, None),
    841: ('opschonen', 'Hoeveel eilanden telt Papoea-Nieuw-Guinea ongeveer?', 600, None),
    844: ('opschonen', 'Hoeveel eilanden telt het Great Barrier Reef?', 900, None),
    850: ('schrappen', None, None, 'Duplicaat van vraag 308.'),
    851: ('schrappen', None, None, 'Duplicaat van vraag 852.'),
    853: ('fout', 'Hoeveel duizend kilometer lang is de Australische kustlijn?', 36,
          'Het opgegeven antwoord 50 klopt niet: de kustlijn is ongeveer 35.900 km.'),
    854: ('exact', 'Hoeveel kilometer lang is de Donau?', 2850, None),
    855: ('exact', 'Hoeveel kilometer lang is de Ganges?', 2525, None),
    856: ('schrappen', None, None, 'Duplicaat van vraag 266.'),
    857: ('schrappen', None, None, 'Duplicaat van vraag 272.'),
    859: ('opschonen', 'Hoeveel kilometer breed is de Kalahariwoestijn ongeveer?', 900, None),
    860: ('exact', 'Hoeveel kilometer lang is de Kongo?', 4700, None),
    861: ('schrappen', None, None, 'Duplicaat van vraag 267.'),
    862: ('exact', 'Hoeveel kilometer lang is de Murray?', 2508, None),
    863: ('exact', 'Hoeveel kilometer lang is de Niger?', 4200, None),
    864: ('schrappen', None, None, 'Duplicaat van vraag 982.'),
    865: ('exact', 'Hoeveel kilometer lang is de Rijn?', 1230, None),
    866: ('exact', 'Hoeveel kilometer lang is de Zambezi?', 2574, None),
    871: ('exact', 'Door hoeveel landen loopt het Andesgebergte?', 7, None),
    872: ('schrappen', None, None, 'Duplicaat van vraag 916.'),
    917: ('exact', 'Door hoeveel landen stroomt de Nijl of een van zijn zijrivieren?', 11, None),
    918: ('exact', 'Hoeveel landen hebben grondgebied in de Sahara?', 10, None),
    920: ('opschonen', 'Hoeveel landen telt Europa?', 50, None),
    923: ('exact', 'Hoeveel landen telt Azië?', 49, None),
    924: ('exact', 'Hoeveel landen telt Midden-Amerika?', 7, None),
    925: ('opschonen', 'Hoeveel landen telt de Sahel-regio?', 10, None),
    929: ('exact', 'Hoeveel meter breed zijn de Victoriawatervallen?', 1708, None),
    930: ('exact', 'Hoeveel meter diep is de Grand Canyon op het diepste punt?', 1857, None),
    931: ('exact', 'Hoeveel meter hoog is de K2?', 8611, None),
    932: ('exact', 'Hoeveel meter hoog is Mount Cook (Aoraki)?', 3724, None),
    934: ('exact', 'Hoeveel meter hoog is Mount Kenya?', 5199, None),
    935: ('exact', 'Hoeveel meter hoog is Mount Kosciuszko, het hoogste punt van Australië?', 2228, None),
    936: ('exact', 'Hoeveel meter hoog is Uluru?', 348, None),
    937: ('exact', 'Hoeveel meter hoog is de Aconcagua?', 6961, None),
    938: ('schrappen', None, None, 'Duplicaat van vraag 34.'),
    939: ('exact', 'Hoeveel meter hoog is de Kilimanjaro?', 5895, None),
    940: ('schrappen', None, None, 'Duplicaat van vraag 981.'),
    941: ('schrappen', None, None, 'Duplicaat van vraag 307.'),
    942: ('exact', 'Hoeveel meter hoog is de Toubkal, de hoogste top van het Atlasgebergte?', 4167, None),
    943: ('exact', 'Hoeveel meter hoog zijn de Victoriawatervallen?', 108, None),
    945: ('exact', 'Hoeveel miljoen inwoners heeft Argentinië?', 46, None),
    946: ('opschonen', 'Hoeveel miljoen inwoners heeft Australië?', 27, None),
    947: ('exact', 'Hoeveel miljoen inwoners heeft Brazilië?', 212, None),
    948: ('opschonen', 'Hoeveel miljoen inwoners heeft Chili?', 20, None),
    949: ('exact', 'Hoeveel miljoen inwoners heeft Colombia?', 52, None),
    950: ('fout', 'Hoeveel miljoen inwoners heeft Mexico?', 130,
          'Het opgegeven antwoord 100 is ruim dertig miljoen te laag.'),
    951: ('opschonen', 'Hoeveel miljoen inwoners heeft Nieuw-Zeeland?', 5, None),
    952: ('exact', 'Hoeveel miljoen inwoners heeft Peru?', 34, None),
    953: ('opschonen', 'Hoeveel nationale parken telt Australië ongeveer?', 500, None),
    954: ('exact', 'Hoeveel nationale parken telt de Verenigde Staten?', 63, None),
    956: ('exact', 'Hoeveel talen erkent India als officiële taal?', 22, None),
    959: ('opschonen', 'Hoeveel procent van Australië is woestijn of droog gebied?', 70, None),
    961: ('exact', 'Hoeveel provincies telt China?', 23, None),
    962: ('schrappen', None, None, 'Duplicaat van vraag 958, die naar prefecturen vraagt.'),
    963: ('exact', 'Hoeveel regio\'s telt Nieuw-Zeeland?', 16, None),
    975: ('schrappen', None, None, 'Duplicaat van vraag 309.'),
    976: ('opschonen', 'Hoeveel miljoen vierkante kilometer beslaat het Amazoneregenwoud?', 6, None),
    984: ('opschonen', 'Hoeveel duizend vierkante kilometer groot is Australië?', 7692, None),

    # ---------------- Geschiedenis ----------------
    994: ('schrappen', None, None, '"Van de val van Saigon tot de hereniging" is geen afgebakende periode.'),
    995: ('opschonen', 'Hoeveel dynastieën telt de Chinese geschiedenis ongeveer?', 13, None),
    1002: ('schrappen', None, None, 'De "rubberboom-crisis" heeft geen vastgelegde duur.'),
    1003: ('exact', 'Hoeveel jaar regeerde Cleopatra VII?', 21, None),
    1005: ('opschonen', 'Hoeveel keer meer piramides heeft Soedan dan Egypte?', 2, None),
    1070: ('schrappen', None, None, 'Onleesbaar geformuleerd.'),

    # ---------------- Milieu, muziek, techniek ----------------
    1090: ('exact', 'Hoeveel delen CO₂ per miljoen delen lucht meet NASA nu?', 425, None),
    1092: ('exact', 'Hoeveel miljoen gnoes trekken mee in de Grote Migratie van de Serengeti?', 2, None),
    1093: ('schrappen', None, None, 'Onbeantwoordbaar: "hoeveel procent van de Sahara was ooit groen".'),
    1105: ('fout', 'Hoeveel Grammy\'s won AC/DC?', 1,
           'Het opgegeven antwoord 0 klopt niet: AC/DC won er één, in 2010.'),
    1108: ('exact', 'Hoeveel studioalbums bracht Midnight Oil uit?', 13, None),
    1112: ('opschonen', 'Hoeveel muzikanten telt een klassieke mariachiband?', 10, None),
    1115: ('exact', 'Hoeveel pianosonates schreef Beethoven?', 32, None),
    1117: ('fout', 'Hoeveel snaren heeft de Ethiopische krar?', 6,
           'Het opgegeven antwoord 10 klopt niet: een krar heeft er vijf of zes.'),
    1118: ('exact', 'Hoeveel snaren heeft een Indiase sitar?', 20, None),
    1120: ('schrappen', None, None, 'Duplicaat van vraag 1121 over dezelfde kora.'),
    1122: ('exact', 'Hoeveel snaren heeft een Chinese guzheng?', 21, None),
    1129: ('exact', 'Hoeveel studioalbums bracht Kylie Minogue uit?', 16, None),
    1133: ('exact', 'Hoeveel symfonieën schreef Mozart?', 41, None),
    1137: ('opschonen', 'Hoeveel kilometer boven de aarde ligt de Kármánlijn, de grens van de ruimte?', 100, None),
    1138: ('opschonen', 'Hoeveel meter diep is de Challengerdiepte in de Marianentrog?', 10935, None),
    1372: ('opschonen', 'Hoeveel kilometer lang is een halve marathon?', 21, None),
    1376: ('schrappen', None, None, 'Er bestaat geen toernooi met die naam waaraan landen meedoen.'),
    1424: ('fout', 'Hoeveel dagen duurde de Apollo 11-missie?', 8,
           'Het opgegeven antwoord 10 klopt niet: de missie duurde acht dagen.'),
    1444: ('opschonen', 'Hoeveel miljoen kilometer is de gemiddelde afstand van de aarde tot de zon?', 150, None),
    1455: ('exact', 'Hoeveel kilometer per uur haalt de Shanghai Maglev?', 431, None),
    1481: ('opschonen', 'Hoeveel duizend beeldpunten telt een Full HD-scherm?', 2074, None),

    # ---------------- Nederland ----------------
    1145: ('exact', 'Hoeveel doelpunten maakte Robin van Persie voor het Nederlands elftal?', 50, None),
    1147: ('exact', 'Hoeveel Nederlandse Nobelprijswinnaars zijn er?', 21, None),
    1154: ('opschonen', 'Hoeveel duizend bladzijden telt het Woordenboek der Nederlandsche Taal?', 45, None),
    1159: ('schrappen', None, None, 'Amsterdam is één gemeente zonder dorpen.'),
    1160: ('schrappen', None, None, 'Het aantal dozen chocoladeletters per persoon is niet vastgelegd.'),
    1162: ('exact', 'Hoeveel duizend inwoners heeft Rotterdam?', 670, None),
    1166: ('schrappen', None, None, 'Een gemiddelde per seizoen hangt af van welke seizoenen je meetelt.'),
    1167: ('exact', 'Hoeveel graden Celsius is de gemiddelde zomertemperatuur in Nederland?', 18, None),
    1168: ('schrappen', None, None, 'Water kookt niet anders in een Nederlandse keuken.'),
    1169: ('schrappen', None, None, 'Het aantal grafkelders is niet verifieerbaar.'),
    1173: ('exact', 'Hoeveel duizend inwoners heeft Amsterdam?', 933, None),
    1180: ('exact', 'Hoeveel duizend kilometer fietspad telt Nederland?', 35, None),
    1182: ('schrappen', None, None, 'De Bollenstreek heeft geen gedefinieerde kustlijn.'),
    1183: ('exact', 'Hoeveel kilometer lang is de Elfstedentocht?', 199, None),
    1185: ('opschonen', 'Hoeveel kilometer van de Maas ligt in Nederland?', 250, None),
    1186: ('exact', 'Hoeveel kilometer lang is het metronet van Rotterdam?', 78, None),
    1187: ('schrappen', None, None, 'Duplicaat van vraag 412.'),
    1190: ('schrappen', None, None, 'Vraagt kilometers maar wil tientallen meters.'),
    1192: ('schrappen', None, None, 'Vraagt kilometers maar wil tientallen meters.'),
    1196: ('opschonen', 'Hoeveel kilometer lang is de Hanzelijn tussen Lelystad en Zwolle?', 50, None),
    1197: ('exact', 'Hoeveel vierkante kilometer groot is de provincie Utrecht?', 1449, None),
    1208: ('opschonen', 'Hoeveel liter melk drinkt een Nederlander per jaar?', 50, None),
    1210: ('schrappen', None, None, 'Duplicaat van vraag 415.'),
    1215: ('exact', 'Hoeveel meter hoog is De Zalmhaven in Rotterdam?', 215, None),
    1216: ('schrappen', None, None, 'Onleesbaar geformuleerd.'),
    1217: ('opschonen', 'Hoeveel meter lang is het cruiseschip Rotterdam?', 300, None),
    1219: ('exact', 'Hoeveel miljard euro bedraagt het Nederlandse defensiebudget?', 21, None),
    1220: ('exact', 'Hoeveel miljoen koeien telt Nederland?', 4, None),
    1223: ('exact', 'Hoeveel molens staan er op de Zaanse Schans?', 8, None),
    1224: ('opschonen', 'Hoeveel musea telt Amsterdam ongeveer?', 80, None),
    1226: ('schrappen', None, None, 'Duplicaat van vraag 1227.'),
    1228: ('opschonen', 'Hoeveel procent van de Nederlanders woont in een rijtjeshuis?', 30, None),
    1229: ('opschonen', 'Hoeveel procent van de Nederlanders fietst dagelijks?', 60, None),
    1231: ('opschonen', 'Hoeveel procent van de Nederlanders woont in de Randstad?', 40, None),
    1232: ('schrappen', None, None, '"Ritten in honderden" is onleesbaar.'),
    1233: ('opschonen', 'Hoeveel schaatsbanen van 400 meter telt Nederland?', 20, None),
    1236: ('schrappen', None, None, 'Het aantal stenen per vierkante meter ligt niet vast.'),
    1244: ('exact', 'Hoeveel dagvlindersoorten komen voor in Nederland?', 53, None),
    1246: ('schrappen', None, None, 'Onleesbaar geformuleerd.'),

    # ---------------- Politiek ----------------
    1249: ('exact', 'Hoeveel miljoen inwoners heeft China?', 1410, 'In miljarden vragen dwingt tot afronden op halve eenheden.'),
    1250: ('exact', 'Hoeveel miljoen inwoners heeft India?', 1440, None),
    1265: ('exact', 'Hoeveel landen gebruiken de West-Afrikaanse CFA-frank?', 8, None),
    1268: ('exact', 'Hoeveel landen telt Oceanië?', 14, None),
    1269: ('exact', 'Hoeveel landen zijn lid van de CELAC?', 33, None),
    1271: ('exact', 'Hoeveel landen zijn lid van het Pacific Islands Forum?', 18, None),
    1276: ('exact', 'Hoeveel landen zijn lid van de Raad van Europa?', 46, None),
    1294: ('exact', 'Hoeveel zetels telt het Australische Huis van Afgevaardigden?', 151, None),
}
