# -*- coding: utf-8 -*-
"""Netto — handmatige herbeoordeling van onbevestigde bronnen, blok 2.

Gebouwen en infrastructuur, en geografie. Vervolg op bronnen_onbevestigd1.py.

In dit blok staan de meeste Britannica-adressen. Die zijn niet op te halen door
botdetectie, maar het onderwerp klopt wel. Waar het antwoord vaststaat is de
bron vervangen door een pagina die wel te controleren is; waar het antwoord van
de telwijze afhangt — hoeveel landen aan een zee grenzen, bijvoorbeeld — staat
"natellen", want dan bevestigt geen enkele bron het getal als getal.
"""

O2 = {
    # ================= Gebouwen en infrastructuur =================
    22: ('bevestigd', 'https://en.wikipedia.org/wiki/Burj_Khalifa',
         'De Burj Khalifa telt 2909 traptreden van de begane grond tot de 160e verdieping.'),
    29: ('bevestigd', 'https://en.wikipedia.org/wiki/Panama_Canal',
         'Het Panamakanaal is 82 kilometer lang.'),
    221: ('bevestigd', 'https://www.toureiffel.paris/en/the-monument/key-figures',
          'De Eiffeltoren zet bij warmte tot ongeveer vijftien centimeter uit. De oude bron '
          'verwees naar een UNESCO-werelderfgoedlijst.'),
    222: ('bevestigd', 'https://en.wikipedia.org/wiki/Hagia_Sophia',
          'De bouw liep van 532 tot 537, bijna vijf jaar.'),
    225: ('bevestigd', 'https://en.wikipedia.org/wiki/Big_Ben',
          'De Great Bell weegt 13,7 ton.'),
    226: ('bevestigd', 'https://en.wikipedia.org/wiki/Eiffel_Tower',
          'De toren telt ongeveer 2,5 miljoen klinknagels.'),
    235: ('bevestigd', 'https://en.wikipedia.org/wiki/Akashi_Kaiky%C5%8D_Bridge',
          'De brug is in totaal 3911 meter lang.'),
    238: ('bevestigd', 'https://en.wikipedia.org/wiki/Panama_Canal',
          'Voor de aanleg werd ongeveer 210 miljoen kubieke meter grond verzet.'),
    240: ('bevestigd', 'https://en.wikipedia.org/wiki/Taj_Mahal',
          'Het mausoleum heeft vier minaretten, een op elke hoek van het platform.'),
    241: ('bevestigd', 'https://en.wikipedia.org/wiki/Giza_pyramid_complex',
          'Het complex kent drie hoofdpiramides: Cheops, Chefren en Mykerinos.'),
    246: ('bevestigd', 'https://en.wikipedia.org/wiki/Empire_State_Building',
          'Van de begane grond naar de 86e verdieping zijn het 1576 treden.'),
    247: ('bevestigd', 'https://en.wikipedia.org/wiki/Statue_of_Liberty',
          'De wenteltrap naar de kroon telt 354 treden.'),
    251: ('bevestigd', 'https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza',
          'De piramide bestaat uit ongeveer 2,3 miljoen blokken.'),
    252: ('bevestigd', 'https://whc.unesco.org/en/list/1321/',
          'De site telt zeventien onderdelen. De oude verwijzing had geen adres.'),
    776: ('bevestigd', 'https://en.wikipedia.org/wiki/Colosseum',
          'De bouw liep van 72 tot 80, ongeveer acht jaar.'),
    783: ('fout', 'https://www.goldengate.org/bridge/history-research/statistics-data/design-construction-stats/',
          'De 128.000 kilometer staaldraad zit in beide hoofdkabels samen, niet in een. Per '
          'kabel is het ongeveer 64.500 kilometer.'),
    785: ('bevestigd', 'https://en.wikipedia.org/wiki/Burj_Khalifa',
          'De toren staat op palen van ongeveer vijftig meter diep.'),
    793: ('bevestigd', 'https://en.wikipedia.org/wiki/Petronas_Towers',
          'De torens zijn 451,9 meter hoog tot de top van de spits.'),
    803: ('bevestigd', 'https://en.wikipedia.org/wiki/Akashi_Kaiky%C5%8D_Bridge',
          'De hoofdoverspanning meet 1991 meter.'),
    806: ('onbruikbaar', 'https://en.wikipedia.org/wiki/Giza_pyramid_complex',
          'Dubbel met vraag 241, en "ongeveer" past niet bij een exact getal. Gizeh telt drie '
          'hoofdpiramides maar met de koninginnenpiramides erbij negen.'),
    816: ('bevestigd', 'https://en.wikipedia.org/wiki/Sydney_Opera_House',
          'Het dak is bedekt met 1.056.006 tegels, afgerond een miljoen. De oude bron verwees '
          'naar een UNESCO-werelderfgoedlijst.'),
    817: ('fout', 'https://www.toureiffel.paris/en/the-monument/key-figures',
          'De 7300 ton klopt, maar het materiaal niet: de Eiffeltoren is van puddelijzer, niet '
          'van staal. De vraag moet "ijzer" zeggen.'),
    818: ('bevestigd', 'https://en.wikipedia.org/wiki/Eiffel_Tower',
          'Met fundering en liften weegt de toren ongeveer 10.100 ton. De oude bron ging over '
          'diagonalen in veelhoeken.'),
    820: ('bevestigd', 'https://www.toureiffel.paris/en/the-monument/key-figures',
          'Van de begane grond tot de top zijn het 1665 treden.'),
    831: ('bevestigd', 'https://whc.unesco.org/en/list/1321/',
          'De site ligt in zeven landen: Argentinie, Belgie, Duitsland, Frankrijk, India, Japan '
          'en Zwitserland.'),

    # ================= Geografie =================
    31: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Baikal',
         'Het Baikalmeer is 636 kilometer lang.'),
    33: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Tanganyika',
         'Het Tanganyikameer is op het diepste punt 1470 meter diep.'),
    35: ('bevestigd', 'https://en.wikipedia.org/wiki/Antarctica',
         'Ongeveer 98 procent van Antarctica is met ijs bedekt.'),
    37: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Baikal',
         'Het diepste punt ligt op 1642 meter; daarmee is het het diepste meer ter wereld.'),
    60: ('natellen', 'https://en.wikipedia.org/wiki/Plate_tectonics',
         'Platen bewegen tussen ongeveer 10 en 100 millimeter per jaar. Het gemiddelde van '
         '25 millimeter is een afleiding, geen gepubliceerd getal.'),
    257: ('bevestigd', 'https://whc.unesco.org/en/list/1314/',
          'De Waddenzee-site ligt in Nederland, Duitsland en Denemarken.'),
    259: ('natellen', 'https://volcano.si.edu/',
          'De Smithsonian houdt de database bij; het aantal actieve vulkanen hangt af van de '
          'gekozen definitie van actief.'),
    265: ('natellen', 'https://en.wikipedia.org/wiki/Geography_of_Japan',
          'Japan strekt zich over ruwweg drieduizend kilometer uit; het getal hangt af van '
          'welke eilanden je meetelt.'),
    271: ('veroudert', 'https://en.wikipedia.org/wiki/Mammoth_Cave_National_Park',
          'De gekarteerde lengte groeit met elke nieuwe verkenning; inmiddels ruim 685 kilometer.'),
    274: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Victoria',
          'Het Victoriameer is 337 kilometer lang.'),
    275: ('bevestigd', 'https://en.wikipedia.org/wiki/Borneo',
          'Borneo wordt gedeeld door Indonesie, Maleisie en Brunei.'),
    276: ('bevestigd', 'https://en.wikipedia.org/wiki/Germany',
          'Duitsland grenst aan negen landen.'),
    278: ('natellen', 'https://en.wikipedia.org/wiki/Red_Sea',
          'Zes landen liggen aan de Rode Zee zelf; tel je de Golf van Akaba mee, dan komen '
          'Israel en Jordanie erbij en zijn het er acht.'),
    279: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Victoria',
          'Het meer grenst aan Oeganda, Kenia en Tanzania.'),
    281: ('natellen', 'https://en.wikipedia.org/wiki/Adriatic_Sea',
          'Italie, Slovenie, Kroatie, Bosnie en Herzegovina, Montenegro en Albanie; de bron '
          'noemt ze wel maar telt ze niet.'),
    282: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Geneva',
          'Het Meer van Geneve ligt in Zwitserland en Frankrijk.'),
    283: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Titicaca',
          'Het Titicacameer ligt op de grens van Peru en Bolivia.'),
    284: ('onbruikbaar', '',
          'Het antwoord hangt af van de gekozen grensconventie; de oorspronkelijke bron zei dat '
          'zelf al. Geen vaste telling mogelijk.'),
    287: ('bevestigd', 'https://en.wikipedia.org/wiki/United_Kingdom',
          'Engeland, Schotland, Wales en Noord-Ierland.'),
    288: ('bevestigd', 'https://en.wikipedia.org/wiki/Niagara_Falls',
          'Er stroomt gemiddeld ongeveer 2400 kubieke meter per seconde, oftewel 2,4 miljoen '
          'liter. De oude bron was een UNESCO-archiefpagina.'),
    289: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Victoria',
          'Het diepste punt ligt op ongeveer 84 meter.'),
    295: ('bevestigd', 'https://en.wikipedia.org/wiki/States_and_territories_of_Australia',
          'Australie heeft zes staten, naast de territoria.'),
    299: ('bevestigd', 'https://en.wikipedia.org/wiki/Sahara',
          'De Sahara beslaat ongeveer 9,2 miljoen vierkante kilometer.'),
    302: ('veroudert', 'https://nsidc.org/arcticseaicenews/',
          'Het zomerminimum verschilt per jaar en daalt over de lange termijn; rond de vier '
          'miljoen vierkante kilometer in recente jaren.'),
    406: ('natellen', 'https://en.wikipedia.org/wiki/Mount_Everest',
          'De opheffing wordt geschat op enkele millimeters per jaar; het exacte getal verschilt '
          'per meting. De oude bron ging over immaterieel erfgoed.'),
    418: ('bevestigd', 'https://en.wikipedia.org/wiki/Provinces_of_the_Netherlands',
          'Nederland heeft twaalf provincies.'),
    565: ('natellen', 'https://en.wikipedia.org/wiki/Iberian_Peninsula',
          'Spanje, Portugal en Andorra liggen er volledig op; met Gibraltar en een strook '
          'Frankrijk erbij worden het er vijf.'),
    566: ('bevestigd', 'https://en.wikipedia.org/wiki/Central_America',
          'Belize, Costa Rica, El Salvador, Guatemala, Honduras, Nicaragua en Panama.'),
    567: ('bevestigd', 'https://en.wikipedia.org/wiki/Equator',
          'De evenaar doorkruist dertien landen.'),
    631: ('bevestigd', 'https://en.wikipedia.org/wiki/Flag_of_South_Africa',
          'De vlag telt zes kleuren: rood, wit, blauw, groen, geel en zwart.'),
    833: ('bevestigd', 'https://en.wikipedia.org/wiki/Danube',
          'De Donau stroomt door tien landen en is daarmee de internationaalste rivier ter wereld.'),
    845: ('bevestigd', 'https://en.wikipedia.org/wiki/Indonesia',
          'De klassieke officiele telling komt op 17.508 eilanden.'),
    852: ('bevestigd', 'https://en.wikipedia.org/wiki/Andes',
          'De Andes is ongeveer zevenduizend kilometer lang.'),
    858: ('bevestigd', 'https://en.wikipedia.org/wiki/Great_Wall_of_China',
          'Het Chinese onderzoek uit 2012 kwam uit op 21.196 kilometer.'),
    869: ('bevestigd', 'https://en.wikipedia.org/wiki/Mediterranean_Sea',
          'De kustlijn meet ongeveer 46.000 kilometer.'),
    899: ('bevestigd', 'https://en.wikipedia.org/wiki/Austria',
          'Oostenrijk grenst aan acht landen.'),
    912: ('natellen', 'https://en.wikipedia.org/wiki/Mediterranean_Sea',
          'De telling komt op 21 of 22, afhankelijk van of Palestina wordt meegeteld.'),
    913: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Tanganyika',
          'Burundi, Congo-Kinshasa, Tanzania en Zambia.'),
    915: ('bevestigd', 'https://en.wikipedia.org/wiki/Black_Sea',
          'Bulgarije, Georgie, Roemenie, Rusland, Turkije en Oekraine.'),
    916: ('natellen', 'https://en.wikipedia.org/wiki/Amazon_basin',
          'Acht landen plus Frans-Guyana, dat geen land is maar wel grondgebied heeft.'),
    926: ('natellen', 'https://en.wikipedia.org/wiki/Arabian_Peninsula',
          'Zeven landen worden er doorgaans toe gerekend, maar de grens naar Irak en Jordanie '
          'is een kwestie van definitie.'),
    927: ('bevestigd', 'https://whc.unesco.org/en/list/1187/',
          'De Struve-boog loopt door tien landen.'),
    960: ('bevestigd', 'https://en.wikipedia.org/wiki/Amazon_basin',
          'Ongeveer zestig procent van het bekken ligt in Brazilie.'),
    977: ('bevestigd', 'https://en.wikipedia.org/wiki/Greenland',
          'Groenland meet ongeveer 2.166.000 vierkante kilometer.'),
    978: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Baikal',
          'Het Baikalmeer beslaat 31.700 vierkante kilometer.'),
    979: ('bevestigd', 'https://en.wikipedia.org/wiki/Lake_Victoria',
          'Het Victoriameer beslaat ongeveer 68.800 tot 69.500 vierkante kilometer.'),
    980: ('bevestigd', 'https://oceanservice.noaa.gov/facts/oceandepth.html',
          'De gemiddelde diepte van de oceanen is ongeveer 3688 meter.'),
    981: ('bevestigd', 'https://en.wikipedia.org/wiki/Mont_Blanc',
          'De Mont Blanc is 4808 meter hoog.'),
    982: ('bevestigd', 'https://en.wikipedia.org/wiki/Nile',
          'De Nijl is ongeveer 6650 kilometer lang.'),
    985: ('bevestigd', 'https://en.wikipedia.org/wiki/Caspian_Sea',
          'De Kaspische Zee beslaat ongeveer 371.000 vierkante kilometer.'),
    1482: ('bevestigd', 'https://en.wikipedia.org/wiki/Alpine_Convention',
           'De Alpenconventie is ondertekend door acht landen.'),
}
