# -*- coding: utf-8 -*-
"""Netto — handmatige bronnen, derde blok: geografie en geschiedenis.

Bij de grensvragen is bewust "natellen" gekozen. Het Wikipedia-artikel over
Argentinie somt de vijf buurlanden op zonder ergens het woord vijf te schrijven.
De bron deugt en de telling is in tien seconden te doen, maar hij is niet
machinaal te bevestigen. Dat eerlijk benoemen is beter dan doen alsof het getal
er staat.
"""

B3 = {
    # ================= Geografie =================
    344: ('natellen', 'https://www.google.com/maps/dir/Amsterdam/Parijs',
          'Routeplanners geven 500 tot 520 km, afhankelijk van de gekozen route.'),
    834: ('natellen', 'https://en.wikipedia.org/wiki/List_of_African_countries_by_coastline',
          'De lijst is te tellen; drieentwintig Afrikaanse landen grenzen aan de Atlantische Oceaan.'),
    835: ('natellen', 'https://en.wikipedia.org/wiki/Mediterranean_Sea',
          'Marokko, Algerije, Tunesie, Libie, Egypte en het betwiste Westelijke Sahara-gebied.'),
    836: ('natellen', 'https://en.wikipedia.org/wiki/Red_Sea',
          'Egypte, Soedan, Eritrea, Djibouti aan Afrikaanse zijde, plus Saoedi-Arabie en Jemen.'),
    838: ('bevestigd', 'https://statistiques.public.lu/en.html',
          'Luxemburg telt ruim 660.000 inwoners.'),
    841: ('natellen', 'https://en.wikipedia.org/wiki/Papua_New_Guinea',
          'Schattingen rond de zeshonderd eilanden; er is geen officiele telling.'),
    846: ('natellen', 'https://en.wikipedia.org/wiki/List_of_island_countries',
          'Kaapverdie, Comoren, Madagaskar, Mauritius, Sao Tome en Principe en de Seychellen.'),
    848: ('bevestigd', 'https://en.wikipedia.org/wiki/New_Zealand',
          'Nieuw-Zeeland bestaat uit twee hoofdeilanden, het Noorder- en het Zuidereiland.'),
    853: ('bevestigd', 'https://www.ga.gov.au/scientific-topics/national-location-information/dimensions',
          'Geoscience Australia geeft ongeveer 35.900 km kustlijn.'),
    859: ('natellen', 'https://en.wikipedia.org/wiki/Kalahari_Desert',
          'De Kalahari meet ongeveer 900 bij 1000 km; de breedte hangt af van de meetrichting.'),
    868: ('bevestigd', 'https://en.wikipedia.org/wiki/Coastline_of_Canada',
          'Canada heeft met 202.080 km de langste kustlijn ter wereld.'),
    871: ('natellen', 'https://en.wikipedia.org/wiki/Andes',
          'Venezuela, Colombia, Ecuador, Peru, Bolivia, Chili en Argentinie.'),
    875: ('natellen', 'https://nl.wikipedia.org/wiki/Argentini%C3%AB',
          'Chili, Bolivia, Paraguay, Brazilie en Uruguay.'),
    880: ('natellen', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo',
          'Negen buurlanden; het artikel somt ze op.'),
    884: ('natellen', 'https://en.wikipedia.org/wiki/Ethiopia',
          'Eritrea, Djibouti, Somalie, Kenia, Zuid-Soedan en Soedan.'),
    885: ('natellen', 'https://nl.wikipedia.org/wiki/Frankrijk',
          'Belgie, Luxemburg, Duitsland, Zwitserland, Italie, Monaco, Spanje en Andorra.'),
    887: ('natellen', 'https://en.wikipedia.org/wiki/Guatemala',
          'Mexico, Belize, Honduras en El Salvador.'),
    888: ('natellen', 'https://en.wikipedia.org/wiki/Honduras',
          'Guatemala, El Salvador en Nicaragua.'),
    890: ('natellen', 'https://en.wikipedia.org/wiki/Cameroon',
          'Nigeria, Tsjaad, Centraal-Afrikaanse Republiek, Congo-Brazzaville, Gabon en '
          'Equatoriaal-Guinea.'),
    891: ('natellen', 'https://en.wikipedia.org/wiki/Kenya',
          'Ethiopie, Somalie, Tanzania, Oeganda en Zuid-Soedan.'),
    894: ('natellen', 'https://en.wikipedia.org/wiki/Mozambique',
          'Tanzania, Malawi, Zambia, Zimbabwe, Zuid-Afrika en Eswatini.'),
    898: ('natellen', 'https://en.wikipedia.org/wiki/Uganda',
          'Zuid-Soedan, Kenia, Tanzania, Rwanda en Congo-Kinshasa.'),
    906: ('natellen', 'https://nl.wikipedia.org/wiki/Spanje',
          'Frankrijk, Andorra, Portugal, Gibraltar en Marokko bij Ceuta en Melilla. '
          'De telling hangt ervan af of je Gibraltar en de exclaves meerekent.'),
    907: ('natellen', 'https://en.wikipedia.org/wiki/Tanzania',
          'Kenia, Oeganda, Rwanda, Burundi, Congo-Kinshasa, Zambia, Malawi en Mozambique.'),
    911: ('natellen', 'https://en.wikipedia.org/wiki/South_Africa',
          'Namibie, Botswana, Zimbabwe, Mozambique, Eswatini en Lesotho.'),
    919: ('natellen', 'https://en.wikipedia.org/wiki/Mediterranean_Sea',
          'Het artikel somt de aanliggende landen op; rond de tweeentwintig.'),
    920: ('natellen', 'https://en.wikipedia.org/wiki/List_of_sovereign_states_in_Europe',
          'De telling loopt van 44 tot 50, afhankelijk van hoe je transcontinentale landen rekent.'),
    921: ('natellen', 'https://en.wikipedia.org/wiki/Melanesia',
          'Fiji, Papoea-Nieuw-Guinea, de Salomonseilanden en Vanuatu.'),
    923: ('bevestigd', 'https://en.wikipedia.org/wiki/Asia',
          'Azie wordt onderverdeeld in negenenveertig landen.'),
    924: ('natellen', 'https://en.wikipedia.org/wiki/Central_America',
          'Belize, Costa Rica, El Salvador, Guatemala, Honduras, Nicaragua en Panama.'),
    925: ('natellen', 'https://en.wikipedia.org/wiki/Sahel',
          'De afbakening van de Sahel verschilt per bron; rond de tien landen.'),
    931: ('bevestigd', 'https://en.wikipedia.org/wiki/K2', 'De K2 meet 8611 meter.'),
    943: ('bevestigd', 'https://whc.unesco.org/en/list/509/',
          'De Victoriawatervallen zijn 108 meter hoog.'),
    949: ('natellen', 'https://www.dane.gov.co/', 'Het Colombiaanse bureau voor de statistiek '
          'publiceert het inwonertal; rond de 52 miljoen.'),
    950: ('natellen', 'https://www.inegi.org.mx/', 'INEGI publiceert het Mexicaanse inwonertal; '
          'rond de 130 miljoen.'),
    951: ('natellen', 'https://www.stats.govt.nz/', 'Stats NZ publiceert het inwonertal; rond de '
          'vijf miljoen.'),
    954: ('bevestigd', 'https://www.nps.gov/aboutus/national-park-system.htm',
          'De National Park Service beheert 63 nationale parken.'),
    959: ('natellen', 'https://www.ga.gov.au/', 'Ongeveer zeventig procent van Australie is '
          'woestijn of semi-aride; de afbakening verschilt per definitie.'),
    963: ('bevestigd', 'https://www.localcouncils.govt.nz/', 'Nieuw-Zeeland telt zestien regios.'),
    964: ('bevestigd', 'https://en.wikipedia.org/wiki/Federated_States_of_Micronesia',
          'Vier deelstaten: Yap, Chuuk, Pohnpei en Kosrae.'),
    966: ('bevestigd', 'https://www.usa.gov/flag',
          'Vijftig sterren, een voor elke staat.'),
    968: ('natellen', 'https://www.australia.gov.au/',
          'Het Noordelijk Territorium en het Australisch Hoofdstedelijk Territorium; met de '
          'externe territoria erbij zijn het er meer.'),
    969: ('bevestigd', 'https://www.australia.gov.au/', 'Australie kent drie tijdzones.'),
    970: ('bevestigd', 'https://www.stats.govt.nz/', 'Nieuw-Zeeland kent twee tijdzones, met de '
          'Chathameilanden apart.'),
    972: ('bevestigd', 'https://www.nist.gov/pml/time-and-frequency-division',
          'Het vasteland van de VS kent vier tijdzones.'),
    984: ('bevestigd', 'https://www.ga.gov.au/scientific-topics/national-location-information/dimensions',
          'Australie beslaat 7.692.024 vierkante kilometer.'),
    1138: ('bevestigd', 'https://en.wikipedia.org/wiki/Challenger_Deep',
           'De Challengerdiepte meet ongeveer 10.935 meter.'),
    1162: ('natellen', 'https://www.cbs.nl/nl-nl/cijfers/detail/70072ned',
           'Het CBS publiceert inwonertallen per gemeente.'),
    1167: ('natellen', 'https://www.knmi.nl/nederland-nu/klimatologie',
           'Het KNMI publiceert maandgemiddelden; de zomer zit rond de 17 a 18 graden.'),
    1173: ('natellen', 'https://www.cbs.nl/nl-nl/cijfers/detail/70072ned',
           'Zelfde CBS-tabel; Amsterdam zit rond de 930.000 inwoners.'),
    1185: ('natellen', 'https://www.rijkswaterstaat.nl/water/vaarwegenoverzicht/maas',
           'Van de ruim 900 km Maas ligt ongeveer 250 km in Nederland.'),
    1193: ('natellen', 'https://www.waddenzee.nl/',
           'De kustlengte van de Waddeneilanden hangt af van de meetmethode.'),
    1197: ('bevestigd', 'https://www.provincie-utrecht.nl/',
           'De provincie Utrecht beslaat ongeveer 1449 vierkante kilometer.'),
    1218: ('bevestigd', 'https://nl.wikipedia.org/wiki/Zuidplaspolder',
           'Het diepste punt ligt bij Nieuwerkerk aan den IJssel, 6,76 meter onder NAP.'),
    1227: ('natellen', 'https://www.rijkswaterstaat.nl/',
           'Ongeveer een kwart van Nederland ligt onder zeeniveau; de telling hangt af van de '
           'gekozen referentiehoogte.'),
    1231: ('natellen', 'https://www.cbs.nl/nl-nl/cijfers/detail/70072ned',
           'Het aandeel Randstadbewoners is uit de CBS-cijfers af te leiden.'),
    1238: ('bevestigd', 'https://www.rijksoverheid.nl/onderwerpen/grondwet-en-statuut/vlag',
           'De Nederlandse vlag heeft drie horizontale banen.'),
    1250: ('natellen', 'https://censusindia.gov.in/',
           'Het Indiase inwonertal ligt rond de 1,44 miljard en groeit.'),
    1268: ('natellen', 'https://en.wikipedia.org/wiki/Oceania',
           'Veertien onafhankelijke landen; de telling hangt af van welke gebieden je meerekent.'),

    # ================= Geschiedenis =================
    986: ('bevestigd', 'https://www.nationalww2museum.org/students-teachers/student-resources/research-starters/research-starters-worldwide-deaths-world-war',
          'Ongeveer 405.000 Amerikaanse militairen kwamen om.'),
    996: ('bevestigd', 'https://www.nps.gov/civilwar/facts.htm',
          'De Amerikaanse Burgeroorlog duurde van 1861 tot 1865.'),
    998: ('bevestigd', 'https://en.wikipedia.org/wiki/Nigerian_Civil_War',
          'De Biafra-oorlog duurde van 1967 tot 1970.'),
    1007: ('bevestigd', 'https://european-union.europa.eu/principles-countries-history/history-eu_nl',
           'Zes landen ondertekenden het Verdrag van Rome: Belgie, Duitsland, Frankrijk, Italie, '
           'Luxemburg en Nederland.'),
    1008: ('bevestigd', 'https://www.nato.int/cps/en/natohq/topics_52044.htm',
           'De NAVO begon in 1949 met twaalf leden.'),
    1011: ('bevestigd', 'https://www.nationalww2museum.org/students-teachers/student-resources/research-starters/research-starters-us-military-numbers',
           'Ruim zestien miljoen Amerikanen dienden in de Tweede Wereldoorlog.'),
    1144: ('natellen', 'https://www.hollandsewaterlinies.nl/',
           'De Oude Hollandse Waterlinie, de Nieuwe Hollandse Waterlinie en de Stelling van '
           'Amsterdam worden verschillend geteld.'),
    1147: ('natellen', 'https://www.nobelprize.org/prizes/lists/all-nobel-prizes/',
           'De Nobelstichting publiceert alle laureaten; de Nederlandse zijn eruit te tellen.'),
    1194: ('bevestigd', 'https://www.koninklijkhuis.nl/',
           'Willem-Alexander heeft drie dochters.'),
    1203: ('onbruikbaar', '', 'De VOC kocht geen landen aan; de vraag berust op een onjuiste '
           'premisse en het antwoord nul maakt elke deelsom stuk.'),
}
